const DEFAULT_PROJECTS = [
    {
        "id": "portfolio-2023-2024",
        "title": "Portfolio 2023-2024",
        "subtitle": "Project Update",
        "tags": "design, architecture, art",
        "shortDescription": "",
        "about": "",
        "approach": "",
        "conclusion": "",
        "roles": [],
        "ctaLabel": "View Project",
        "ctaHref": "project-detail.html?id=portfolio-2023-2024",
        "bannerImage": "https://lh3.googleusercontent.com/d/1q2Y-p0RNHTnckce3ha-wbKOVH0y8YGGO",
        "images": [
            "https://lh3.googleusercontent.com/d/1IwJ0lat1YGZzm7TY4HVR-A8tS9IJVJqf",
            "https://lh3.googleusercontent.com/d/12qmFew59LZ6U6CqCr4gVf8OFn0GSE_TS",
            "https://lh3.googleusercontent.com/d/1NzsZNwwiJuM3uuMTTUd146qUaUOQEJQC",
            "https://lh3.googleusercontent.com/d/1d1tYg0Se6mb_ubdoZ92dd97d5d5soJ3P",
            "https://lh3.googleusercontent.com/d/1fP-2EPmJjprO2YBqDZmxnalFNVCjkSln",
            "https://lh3.googleusercontent.com/d/1tK0pX36Efb1e4Cex5PrjHFHTqq368r5x",
            "https://lh3.googleusercontent.com/d/1uedYCioUe2Wf-wFxv2atoRMjJ4_ig-tC",
            "https://lh3.googleusercontent.com/d/1Zo4AkO_n_wL_848pfVRnMcgtrAtrKujK",
            "https://lh3.googleusercontent.com/d/1l194iY4DMAdzv2AA831RMqSZzPpR_yCG",
            "https://lh3.googleusercontent.com/d/1M_OFi0x7m_SdWcFC4mgrtQXP3T_xZKgo",
            "https://lh3.googleusercontent.com/d/1yDT2LptocGtSB-G0ccc-v-acXagSNaIR",
            "https://lh3.googleusercontent.com/d/1s4KPNVs1F7wwRi9D8jut0cCt8bBPwOr-",
            "https://lh3.googleusercontent.com/d/1RZKpMVj7gQ5Prl64mWzWE2zXKFjWDiFK",
            "https://lh3.googleusercontent.com/d/1wxJKJr6_yoB17kMTN6fEjn-sfrAMGDFM",
            "https://lh3.googleusercontent.com/d/1pjXXyme4D0hAxIWNXPbctUB6nQVyangs",
            "https://lh3.googleusercontent.com/d/12g-83Z9o1KnKzSKhDd5N-YcRcql8qQRw",
            "https://lh3.googleusercontent.com/d/1xgu0ZqgZBCJmqFLR63ejQVkGGFHqnxZa",
            "https://lh3.googleusercontent.com/d/15fP1WVMiAkZmCsBHyDt9TJh--uYfl0Ch",
            "https://lh3.googleusercontent.com/d/13TjyCl9wvXopOIkdFB3eBBOxvJWvC7Nb",
            "https://lh3.googleusercontent.com/d/1vjsf7jbgRmvMyNayL8XpsAr271Z330Pr",
            "https://lh3.googleusercontent.com/d/19Byw5V3TkSDb2N4Xur5bSqwnFHHQNuSr",
            "https://lh3.googleusercontent.com/d/1sDl6Nv29HmeVuBvrSUeNMqwE-XR_IOWk",
            "https://lh3.googleusercontent.com/d/13q6YqvA6ecl8kVyJo1cx5_Uub0stUMgt",
            "https://lh3.googleusercontent.com/d/1jkbd1gCZ5T2kas-wN_SgSMu73VDlzYVJ",
            "https://lh3.googleusercontent.com/d/1tb7ycEKwr7bUm31_px5HOEpEJ2eRj0vP",
            "https://lh3.googleusercontent.com/d/1QWCzDL7KSPL5Y1fAa9A76jSEyoK7yHbK",
            "https://lh3.googleusercontent.com/d/1DWwowz4WlH8wVFNkVLUJJOKEjZyFFrca",
            "https://lh3.googleusercontent.com/d/1pQlC61YPX45fj-GbtXrRpBkpydgFojdz"
        ],
        "videoUrl": "",
        "order": 10,
        "ishidden": false,
        "isFeatured": false,
        "frameWidth": "",
        "frameHeight": "",
        "frameGlassEffect": "",
        "frameColor": "",
        "spotlightColor": "",
        "spotlightIntensity": "",
        "frameBorder": "",
        "frameShadow": "",
        "client": "",
        "role": "",
        "year": "",
        "location": "",
        "softwareUsed": "",
        "awards": "",
        "linkInstagram": "",
        "linkBehance": "",
        "linkVideo": "",
        "linkLive": "",
        "linkFigma": "",
        "linkPdf": "",
        "bannerUrl": "https://lh3.googleusercontent.com/d/1q2Y-p0RNHTnckce3ha-wbKOVH0y8YGGO"
    },
    {
        "id": "agnipankh-the-last-dragon",
        "title": "Agnipankh — The Last Dragon",
        "subtitle": "AI Visual Storytelling · World Building",
        "tags": "AI, worldbuilding, cinematic, photoshop, storytelling",
        "shortDescription": "A legendary fantasy world pre-visualization utilizing advanced AI tools combined with layout grid design.",
        "about": "Agnipankh needed to present a complex, legendary fantasy world in a way that felt cinematic, historically grounded, yet futuristic. The primary challenge was developing character designs, production layouts, and world features quickly to establish cinematic visual references for production.",
        "approach": "",
        "conclusion": "",
        "roles": [
            "Visual Storytelling Development",
            "Storyboard Development",
            "Creative Concept Visualization"
        ],
        "ctaLabel": "View Project",
        "ctaHref": "project-detail.html?id=agnipankh-the-last-dragon",
        "bannerImage": "https://lh3.googleusercontent.com/d/1jWWrM_c7IK9yooma-C5e0f3MZ6aWW0PS",
        "images": [
            "https://lh3.googleusercontent.com/d/1fCjSQ9m2TUDBlXPFtsAx3q7ps1yHtZsR",
            "https://www.youtube.com/embed/KIlROSA62l0?autoplay=1&mute=1&loop=1&playlist=KIlROSA62l0&controls=0&showinfo=0&autohide=1&modestbranding=1",
            "https://lh3.googleusercontent.com/d/1X8vqWG8COmcY1XyrClls-1Waen-21vvr",
            "https://lh3.googleusercontent.com/d/1Zh7dLf5mMZt76gmmFawOUijq2f-Jxvdx",
            "https://lh3.googleusercontent.com/d/1JHTozp4cjx8nBb7VjoUSORvrcHQmlZf7",
            "https://lh3.googleusercontent.com/d/1OtHlmta_SpT68JJ38oO3-8FW-EiqjpHm",
            "https://lh3.googleusercontent.com/d/1b2FoHUSOEO6Qo_4cU2WBAfMPQEDqd8AP",
            "https://lh3.googleusercontent.com/d/19eTgAY6Ydp8bdhX_h0ciKHkp-MgWn5hv",
            "https://lh3.googleusercontent.com/d/1CHRTFIyTCtwN-ZFcfCmFYLsLgMGmjfyJ",
            "https://lh3.googleusercontent.com/d/1JmXiz7_a_pWISsabocLyw5qFKRUPZ0Hg",
            "https://lh3.googleusercontent.com/d/1v8t5dX79zUehTdU_m0FK_jtwcEyIlzN0",
            "https://lh3.googleusercontent.com/d/1D4PG_6xmcZ3jMJNZ4Uj16wa_QSVlF16M",
            "https://lh3.googleusercontent.com/d/1_ldzjSEIdwb1Vo5nqVUYrBTwHqzHB6AO",
            "https://lh3.googleusercontent.com/d/1poqUsDH7huB5gdbryiqcBYcyw09eXNqO",
            "https://lh3.googleusercontent.com/d/13V8ty_sqxFpD9P6V16tSGzDqiVN0MHXp",
            "https://lh3.googleusercontent.com/d/1zO1icXxlYgM25P5X3VVuBKTTk1qDLXsg",
            "https://lh3.googleusercontent.com/d/1EkE_v-1uximxI8Qup-MOlNqvg-0zCBEX",
            "https://lh3.googleusercontent.com/d/1IAYfI7Wfz-gypEAL8Sjdi16u_h5kYsl2",
            "https://lh3.googleusercontent.com/d/1jWWrM_c7IK9yooma-C5e0f3MZ6aWW0PS",
            "https://lh3.googleusercontent.com/d/1wK4F9U5gwhXRFzkPPjYiLTnXrp4NK3x2",
            "https://lh3.googleusercontent.com/d/1zP9Mjw0p-g_aF4kmZmvv4HonWTK5jFkX",
            "https://lh3.googleusercontent.com/d/1bGg25c2HsVFOJI2f6qIeWu3L9KuOo6fM",
            "https://lh3.googleusercontent.com/d/1qiLKNgstpYRhgjvQeF_PSZ7CMNfJYp_c",
            "https://lh3.googleusercontent.com/d/1i-idFGzGdf98tqLflKA2BKSJ9VAknYv0",
            "https://lh3.googleusercontent.com/d/1ZBGTqbPvnE5MQG9KkDsfB6WotUOUiGCS"
        ],
        "videoUrl": "https://www.youtube.com/embed/wGMyL-B7wt0?autoplay=1&mute=1&loop=1&playlist=wGMyL-B7wt0&controls=0&showinfo=0&autohide=1&modestbranding=1",
        "order": 1,
        "ishidden": false,
        "isFeatured": true,
        "frameWidth": "",
        "frameHeight": "",
        "frameGlassEffect": "",
        "frameColor": "",
        "spotlightColor": "",
        "spotlightIntensity": "",
        "frameBorder": "",
        "frameShadow": "",
        "client": "",
        "role": "",
        "year": "2026",
        "location": "Delhi",
        "softwareUsed": "CHAT GPT, Magnific",
        "awards": "",
        "linkInstagram": "",
        "linkBehance": "",
        "linkVideo": "",
        "linkLive": "",
        "linkFigma": "",
        "linkPdf": "",
        "bannerUrl": "https://lh3.googleusercontent.com/d/1jWWrM_c7IK9yooma-C5e0f3MZ6aWW0PS"
    },
    {
        "id": "all-work",
        "title": "Work",
        "subtitle": "Branding, campaign",
        "tags": "poster, Banner, Logo, press Ads",
        "shortDescription": "",
        "about": "",
        "approach": "",
        "conclusion": "",
        "roles": [],
        "ctaLabel": "View Project",
        "ctaHref": "project-detail.html?id=all-work",
        "bannerImage": "https://lh3.googleusercontent.com/d/1x1OElbFPWwWsKqmOgWfBVtxnaZd-8Kn3",
        "images": [
            "https://lh3.googleusercontent.com/d/1uBF62YORzr1xOhJ1mj26ZMiFfHnqPsJ6",
            "https://lh3.googleusercontent.com/d/1js3XwnQhUjLw13kSTzwXQZCx3Cwlc5t7",
            "https://lh3.googleusercontent.com/d/1np2Ez_PQjNqrGUE4Crep3MYxedDHg-0K",
            "https://lh3.googleusercontent.com/d/1c5lDwUM68GUT9rfWfzW788lIZB4fmLw5",
            "https://lh3.googleusercontent.com/d/10j4DeyILBV6hp2BLPK5z5p8Cvb2ot7lj",
            "https://lh3.googleusercontent.com/d/191K8_kRlIeJyVnPw-hIwS-5RZv0gLrwj",
            "https://lh3.googleusercontent.com/d/1VuY732tppt_koDE33LxaATVr9Wyy0oF_",
            "https://lh3.googleusercontent.com/d/18gHpdjiJSbtB7krTboPQXqWZirYbXsBi",
            "https://lh3.googleusercontent.com/d/1tqohvfHCXvFBkylwRmBDdABw5SyF62L3",
            "https://lh3.googleusercontent.com/d/1ynQAB-qUdJa6WC1nO8yQ3oNxPxQKUiAr",
            "https://lh3.googleusercontent.com/d/1RW8yan_cp3roR9QN7XymWPM6OsnbAnyX",
            "https://lh3.googleusercontent.com/d/1EkHpqhLTgZSPXeVas1472nzAJ9kuqOi6",
            "https://lh3.googleusercontent.com/d/15kTlJ9Z7MbCht24KyKrBV2HXmW9fGwz3",
            "https://lh3.googleusercontent.com/d/1Q2YiHhm1ugmee0YSgzMChGRc1tqdRHsz",
            "https://lh3.googleusercontent.com/d/15l3NbHYX3n3cjxNFElNq1B7ihwtNrcV5",
            "https://lh3.googleusercontent.com/d/1bNUQLqnB1A9ZUV3LS2kF-UYNlIJXI3VW",
            "https://lh3.googleusercontent.com/d/1yVsrLZZRDQuvdUHZreGxfMAImKRgYngm",
            "https://lh3.googleusercontent.com/d/1Tty4MlSIob-tSmqlZiSLRmY5jB_u-7iy",
            "https://lh3.googleusercontent.com/d/14LPFA-IdaLdfAJMgUDHfGOxU6NdK14TT",
            "https://lh3.googleusercontent.com/d/1im6GE6qIpkBP_y2aU9LTib0N2lw7rA5Z",
            "https://lh3.googleusercontent.com/d/1a_6VKJI3-Ot7hvIz8jW6mZ3CAo_Crb4K",
            "https://lh3.googleusercontent.com/d/18Y32tZknv3x08HI0QrCpkgqfojSTwzMO",
            "https://lh3.googleusercontent.com/d/1kJI7T7osWtLZw-7ATLU_cZ4TLKa-x5s9",
            "https://lh3.googleusercontent.com/d/1-hooa91j2zSTFOduY666C0wcn_qp0qNt",
            "https://lh3.googleusercontent.com/d/1dxUlYAHcleahZN6f-07W5U7olk7JnO4S"
        ],
        "videoUrl": "",
        "order": 10,
        "ishidden": false,
        "isFeatured": false,
        "frameWidth": "",
        "frameHeight": "",
        "frameGlassEffect": "",
        "frameColor": "",
        "spotlightColor": "",
        "spotlightIntensity": "",
        "frameBorder": "",
        "frameShadow": "",
        "client": "",
        "role": "",
        "year": "2023-2025",
        "location": "",
        "softwareUsed": "",
        "awards": "",
        "linkInstagram": "",
        "linkBehance": "",
        "linkVideo": "",
        "linkLive": "",
        "linkFigma": "",
        "linkPdf": "",
        "bannerUrl": "https://lh3.googleusercontent.com/d/1x1OElbFPWwWsKqmOgWfBVtxnaZd-8Kn3"
    },
    {
        "id": "amber-fort-light-spectacular",
        "title": "Amber Fort Light Spectacular",
        "subtitle": "Projection Mapping & Light Show",
        "tags": "projection mapping",
        "shortDescription": "A magnificent light and sound spectacular projected onto the historic Amber Fort.",
        "about": "We created an immersive light and sound experience that brings the rich history of Amber Fort to life through stunning projection mapping.",
        "approach": "",
        "conclusion": "",
        "roles": [
            "Creative Direction",
            "Visual Design",
            "Projection Mapping"
        ],
        "ctaLabel": "View Project",
        "ctaHref": "project-detail.html?id=amber-fort-light-spectacular",
        "bannerImage": "https://lh3.googleusercontent.com/d/1EX7sT536YP5pQDZfoxOoINDnwIUrdZc7",
        "images": [
            "https://lh3.googleusercontent.com/d/1G7IUNQXWonNr-gW8puk1qzCXC2E_Vhfw",
            "https://lh3.googleusercontent.com/d/1AgPd4NYQB-gRHPh33xKfGnFLp6rJh4o8",
            "https://lh3.googleusercontent.com/d/1DVETciRQg7zKZJKuJb0JtSlWPm35I0d2",
            "https://lh3.googleusercontent.com/d/1gzAAmYVzcrD7KWrGdetyHDKvaCh4c4LK",
            "https://www.youtube.com/embed/YIO_p2lpWOg?autoplay=1&mute=1&loop=1&playlist=YIO_p2lpWOg&controls=0&showinfo=0&autohide=1&modestbranding=1"
        ],
        "videoUrl": "https://www.youtube.com/embed/6xuKI6d2T8I?autoplay=1&mute=1&loop=1&playlist=6xuKI6d2T8I&controls=0&showinfo=0&autohide=1&modestbranding=1",
        "order": 5,
        "ishidden": false,
        "isFeatured": true,
        "frameWidth": "",
        "frameHeight": "",
        "frameGlassEffect": "",
        "frameColor": "",
        "spotlightColor": "",
        "spotlightIntensity": "",
        "frameBorder": "",
        "frameShadow": "",
        "client": "",
        "role": "GRAPHIC DESIGNER",
        "year": "2026",
        "location": "RAJASTHAN",
        "softwareUsed": "PHOTOSHOP",
        "awards": "",
        "linkInstagram": "",
        "linkBehance": "",
        "linkVideo": "",
        "linkLive": "",
        "linkFigma": "",
        "linkPdf": "",
        "bannerUrl": "https://lh3.googleusercontent.com/d/1EX7sT536YP5pQDZfoxOoINDnwIUrdZc7"
    },
    {
        "id": "baramati-museum",
        "title": "Baramati Museum",
        "subtitle": "Museum",
        "tags": "",
        "shortDescription": "Designed museum graphics and projection mapping visuals for an immersive visitor experience.",
        "about": "Design immersive museum graphics and projection mapping visuals that communicate Baramati's history, development, and cultural significance through engaging visual storytelling while enhancing the overall visitor experience.",
        "approach": "",
        "conclusion": "Successfully delivered cohesive museum graphics and projection mapping content that enhanced visitor engagement, strengthened visual storytelling, and transformed historical narratives into immersive, memorable experiences.",
        "roles": [
            "Designed exhibition graphics",
            "information panels",
            "and visual assets aligned with the museum's narrative and identity. Created projection mapping visuals",
            "developed storytelling sequences",
            "and collaborated to deliver immersive digital experiences."
        ],
        "ctaLabel": "View Project",
        "ctaHref": "project-detail.html?id=baramati-museum",
        "bannerImage": "https://lh3.googleusercontent.com/d/1495IDLLQBmVyYCGCq-M9i68mD_0nPHgQ",
        "images": [
            "https://lh3.googleusercontent.com/d/1dIlIOA9D-K85WiW_i_H_iBRsTqkHyBxR",
            "https://lh3.googleusercontent.com/d/1R2LW82vG2SpQlBvuR-6Z4UFZE8LKm6NT",
            "https://lh3.googleusercontent.com/d/1A5lu4FAfBYo4oU3yUFBnm2IFioJ4NGSC",
            "https://lh3.googleusercontent.com/d/1IlfofLNSfr1IetEytncn-ir5QiBmt6b9",
            "https://lh3.googleusercontent.com/d/1TuPNpqEwFpRZTU3IrKtz0tUKkScFJa3E",
            "https://lh3.googleusercontent.com/d/1KjaDC9Twvyvh6TJzhCMEd5YumdWMR3rH",
            "https://lh3.googleusercontent.com/d/1ShVyTmjJEM_bAQOLqjkhmg4mKe5FLiOL",
            "https://lh3.googleusercontent.com/d/1A9ZRymMl0es8TKFZMQj1JXhMk57OhyVv",
            "https://lh3.googleusercontent.com/d/1sbTLqEyNOtngHffdKe7RN6mqXe_PLueU",
            "https://lh3.googleusercontent.com/d/1v-7Xlkofij6nwdRGQvUTDTAiYKfjgyZ7",
            "https://lh3.googleusercontent.com/d/15DjgRUIHIDiY0RZJt-bReatc9rHVtOtA",
            "https://lh3.googleusercontent.com/d/13Ppy7SB3Zdo2OX2ZWHe8wWNcWztskhY-",
            "https://lh3.googleusercontent.com/d/12Rq2ylfl_EHaAOOH5jdD6nCM6eC8RuOV",
            "https://lh3.googleusercontent.com/d/1CBDv_TlMo2Eyi0vo3M57gOnJTfUBOQUC",
            "https://lh3.googleusercontent.com/d/1D6OPJyidVcehZ372qR4gZ22F_VpXDQdK",
            "https://lh3.googleusercontent.com/d/1SItMd-axpQbyII5orYR7oQDqxH4FtXEM",
            "https://lh3.googleusercontent.com/d/1vttYwMTf2g5HlpFySTsORCQIp9WYLiUy",
            "https://lh3.googleusercontent.com/d/11I6aXmv994OPOffBNntvp5rgXgJlx3tP",
            "https://lh3.googleusercontent.com/d/12yrIUCzAmcVWI_XQXv5MwmLPcOo5iiHu",
            "https://lh3.googleusercontent.com/d/1Ub8DnapW6HDiQbX_ZBqaQg6cMMIjkC7_",
            "https://lh3.googleusercontent.com/d/1_jOEerbkVlYrUE6qF12XzUop6GfwBQDj",
            "https://lh3.googleusercontent.com/d/1uRAPagJOY0B1TSJ5RCw7A-FUXeK5KaL6",
            "https://lh3.googleusercontent.com/d/1eGndeeYpb6xaD6_GfsGPMEqD_NUFPfm1",
            "https://lh3.googleusercontent.com/d/1H5h1bpLhqhQvUNNz51VjDri4DmchSc1s"
        ],
        "videoUrl": "https://www.youtube.com/embed/wQKl2sk80gs?autoplay=1&mute=1&loop=1&playlist=wQKl2sk80gs&controls=0&showinfo=0&autohide=1&modestbranding=1",
        "order": 7,
        "ishidden": false,
        "isFeatured": true,
        "frameWidth": "",
        "frameHeight": "",
        "frameGlassEffect": "",
        "frameColor": "",
        "spotlightColor": "",
        "spotlightIntensity": "",
        "frameBorder": "",
        "frameShadow": "",
        "client": "",
        "role": "Graphic Designer & Projection Mapping Artist",
        "year": "2025",
        "location": "",
        "softwareUsed": "Photoshop, chat GPT",
        "awards": "",
        "linkInstagram": "",
        "linkBehance": "",
        "linkVideo": "",
        "linkLive": "",
        "linkFigma": "",
        "linkPdf": "",
        "bannerUrl": "https://lh3.googleusercontent.com/d/1495IDLLQBmVyYCGCq-M9i68mD_0nPHgQ"
    },
    {
        "id": "bipard-jivika-projection-mapping",
        "title": "Bipard Jivika Projection Mapping",
        "subtitle": "Projection Mapping",
        "tags": "",
        "shortDescription": "Designed immersive projection mapping visuals showcasing the impact of the Jivika initiative.",
        "about": "Create immersive projection mapping visuals that communicate the impact of Jivika initiatives through engaging storytelling, dynamic animations, and visually compelling digital experiences for large-scale projection.",
        "approach": "",
        "conclusion": "Successfully delivered immersive projection mapping visuals that transformed key messages into engaging visual experiences, enhancing audience engagement and effectively communicating the project's impact through digital storytelling.",
        "roles": [
            "Created cinematic projection mapping visuals aligned with the project's narrative",
            "objectives",
            "and projection surface."
        ],
        "ctaLabel": "View Project",
        "ctaHref": "project-detail.html?id=bipard-jivika-projection-mapping",
        "bannerImage": "https://lh3.googleusercontent.com/d/1aCNeATEbrrxdkQeJgpc1y34fG-CGamIv",
        "images": [
            "https://lh3.googleusercontent.com/d/10FEcDV-mhi4StUtjcsG-tzAVBCwnpT7J",
            "https://lh3.googleusercontent.com/d/1wtKY30aPsPom2SmAJBsvNjW6XeeEi9aR",
            "https://lh3.googleusercontent.com/d/12jiHIl4qNNVgeS-VGuUF2ZKNZnROloK3",
            "https://lh3.googleusercontent.com/d/1PpcABuXl2bWpa22HMWUIkY4xjeDLn_B0",
            "https://lh3.googleusercontent.com/d/142qOPnuVC342vE6SGPiQhBo4Vwy24d2b",
            "https://lh3.googleusercontent.com/d/1_4C547SRi50SwIFsSkZkjoV7WsDojEuw",
            "https://lh3.googleusercontent.com/d/1zx9u4M3N2DIiD9xL_wTHvVoBfrTnxPO3",
            "https://lh3.googleusercontent.com/d/1t9pZ_Amw1NkThTN_DVKlY9ubU2doNUTi",
            "https://lh3.googleusercontent.com/d/1GayT-INQ_IMOnlUKw3DVhhN9HnhK5fJ6",
            "https://lh3.googleusercontent.com/d/1Kwvv1Ir8WNeKGjxg1aZZ7Y_NmXSxKyNF",
            "https://lh3.googleusercontent.com/d/1aCNeATEbrrxdkQeJgpc1y34fG-CGamIv",
            "https://www.youtube.com/embed/tIiXS3L5QcU?autoplay=1&mute=1&loop=1&playlist=tIiXS3L5QcU&controls=0&showinfo=0&autohide=1&modestbranding=1"
        ],
        "videoUrl": "https://www.youtube.com/embed/NvvneNluzLE?autoplay=1&mute=1&loop=1&playlist=NvvneNluzLE&controls=0&showinfo=0&autohide=1&modestbranding=1",
        "order": 10,
        "ishidden": false,
        "isFeatured": false,
        "frameWidth": "",
        "frameHeight": "",
        "frameGlassEffect": "",
        "frameColor": "",
        "spotlightColor": "",
        "spotlightIntensity": "",
        "frameBorder": "",
        "frameShadow": "",
        "client": "",
        "role": "Projection Mapping Visual Designer",
        "year": "",
        "location": "",
        "softwareUsed": "",
        "awards": "",
        "linkInstagram": "",
        "linkBehance": "",
        "linkVideo": "",
        "linkLive": "",
        "linkFigma": "",
        "linkPdf": "",
        "bannerUrl": "https://lh3.googleusercontent.com/d/1aCNeATEbrrxdkQeJgpc1y34fG-CGamIv"
    },
    {
        "id": "coffee-india",
        "title": "Coffee India",
        "subtitle": "Campaign",
        "tags": "",
        "shortDescription": "An AI-powered premium coffee campaign blending cinematic storytelling with luxury product visuals.",
        "about": "Create a premium AI-driven coffee campaign that positions India Coffee as a modern lifestyle brand while maintaining a luxurious, aspirational, and visually consistent identity across all campaign creatives.\nA conceptual AI advertising campaign designed to showcase India Coffee through cinematic visuals, premium product storytelling, and luxury lifestyle aesthetics for digital and social media marketing.",
        "approach": "",
        "conclusion": "Successfully created a cohesive AI-powered campaign that elevated the brand's premium identity through cinematic visuals, consistent storytelling, and high-impact product presentation.\n\nOption 2",
        "roles": [
            "AI Campaign Visualization",
            "AI Image Generation",
            "Brand Communication Design",
            "Creative Campaign Execution",
            "Product Hero Visualization"
        ],
        "ctaLabel": "View Project",
        "ctaHref": "project-detail.html?id=coffee-india",
        "bannerImage": "https://lh3.googleusercontent.com/d/1JC7FXedxlI7OlUfgFr5Qk5u5GGmOR5Ri",
        "images": [
            "https://lh3.googleusercontent.com/d/1CKPUY8bWl_S6ldy0cQVHMovXKHPQVRVZ",
            "https://lh3.googleusercontent.com/d/11G0E-IUR029QaFjUdPgFhAJ4USOVYCNa",
            "https://lh3.googleusercontent.com/d/1VfB4Lz-2ogDSXiPPZhHn75QSjHBGQ7C6",
            "https://lh3.googleusercontent.com/d/1RlPghcqXWaHDne8kFBKcWIgPnFVcK63f",
            "https://lh3.googleusercontent.com/d/1o0HNuTjIi83IPj34JOP8oezWep1atqNH",
            "https://lh3.googleusercontent.com/d/1ybTxWpdsRPD9FAOBAs_ivm6d55LVRZyH",
            "https://lh3.googleusercontent.com/d/1rt2wvET8GP1QWBVAnGZVv2iZic2kX4cC",
            "https://lh3.googleusercontent.com/d/1qgZtBReqZA29JH9G97p3AXOlkVr9c2tF",
            "https://lh3.googleusercontent.com/d/1NqNjixy2XlbIoNyNaN6-d5SYVnM11475",
            "https://lh3.googleusercontent.com/d/1vRhJ5zXL31WQcyrZgJPEn91XfPciEtjl",
            "https://lh3.googleusercontent.com/d/1JnJEQTUrFW2AaFOd_CtE8VY2WAGJIJ6_",
            "https://lh3.googleusercontent.com/d/1UsMZvqI0jR7IU1PV6aj_QbSbfalreZyi",
            "https://lh3.googleusercontent.com/d/1EHprjvsyGjVaBrJD4Jq7jAcTCe27cZ8J",
            "https://lh3.googleusercontent.com/d/1nKvYKu9x3OKRXIZLpr4fE2JjoX0NLA75",
            "https://lh3.googleusercontent.com/d/1pXBAFZyV0s20kkF_-951tUPYaZQPf_zk",
            "https://lh3.googleusercontent.com/d/1oDHSpvcFUEfYahdoSqUnlb3O9rvDHcpq",
            "https://lh3.googleusercontent.com/d/1ukeerSOOUC4eFhcC7peXu52dLTp9P-dx",
            "https://lh3.googleusercontent.com/d/13zLRr7qtIlhhmVCGzBxjqJWI7o3zXbId",
            "https://lh3.googleusercontent.com/d/1Ef_Zy-I_Su5CXETbvId0hJVorJtM1hvj",
            "https://lh3.googleusercontent.com/d/1IoRwI9EShv_VJYFT5zgn4ZtfRO1jRv4M",
            "https://lh3.googleusercontent.com/d/1w-F_OLH2R50LrJYgy-sr9YTS38gz3ZAo",
            "https://lh3.googleusercontent.com/d/1-lV3z1AgmpHe3uafFS-Vdv41TNPw0nja",
            "https://lh3.googleusercontent.com/d/1jSWE-9Xl8Yc96LyApPh7vmXOagigd9TF",
            "https://lh3.googleusercontent.com/d/1znO6ePCRbLbww7HPz7SD_7truKCvNpaU",
            "https://lh3.googleusercontent.com/d/1J9ogqLKcNIZmWiWz_-nNrkA_eanym-XH"
        ],
        "videoUrl": "https://www.youtube.com/embed/aV30PVYE9Ss?autoplay=1&mute=1&loop=1&playlist=aV30PVYE9Ss&controls=0&showinfo=0&autohide=1&modestbranding=1",
        "order": 10,
        "ishidden": false,
        "isFeatured": false,
        "frameWidth": "",
        "frameHeight": "",
        "frameGlassEffect": "",
        "frameColor": "",
        "spotlightColor": "",
        "spotlightIntensity": "",
        "frameBorder": "",
        "frameShadow": "",
        "client": "",
        "role": "AI Campaign Visualization",
        "year": "2026",
        "location": "Delhi",
        "softwareUsed": "Chat GPT, Magnific",
        "awards": "",
        "linkInstagram": "",
        "linkBehance": "",
        "linkVideo": "",
        "linkLive": "",
        "linkFigma": "",
        "linkPdf": "",
        "bannerUrl": "https://lh3.googleusercontent.com/d/1JC7FXedxlI7OlUfgFr5Qk5u5GGmOR5Ri"
    },
    {
        "id": "dettol",
        "title": "Dettol Pocket Handwash",
        "subtitle": "Campaign",
        "tags": "",
        "shortDescription": "",
        "about": "Create a visually engaging campaign that highlights the convenience, portability, and trusted protection of Dettol Pocket Handwash while reinforcing the brand’s promise of hygiene anytime, anywhere.",
        "approach": "",
        "conclusion": "Delivered a clean and impactful campaign that effectively highlighted product portability, trusted hygiene, and strong brand recognition through premium AI-generated visuals.",
        "roles": [
            "AI Campaign Visualization Creative Concept Development Product Advertisement Design Brand Visual Identity AI Image Generation"
        ],
        "ctaLabel": "View Project",
        "ctaHref": "project-detail.html?id=dettol",
        "bannerImage": "https://lh3.googleusercontent.com/d/19-7LmwYRIWgD_-OrJhwlHovYgsS3ZRcL",
        "images": [
            "https://lh3.googleusercontent.com/d/1FBaCK2YO7ffNEDopbBLBaxcaN3FW7A8U",
            "https://lh3.googleusercontent.com/d/1pqh5biUzcPTP8iTahZvVKy2jorwsbP_X",
            "https://lh3.googleusercontent.com/d/1tslPcPkHA220F3TP_Ubk2sXCNIHYsS0Z",
            "https://lh3.googleusercontent.com/d/1wnm33yuWQH50fev92y5vGUSfoiS0kCtH",
            "https://lh3.googleusercontent.com/d/1c1MfsO_xcMlrRyIMR395W2u85aBBA3FS",
            "https://lh3.googleusercontent.com/d/1tDHm_wskAuzm23lL1P-Go2TB6DJkw5EX",
            "https://lh3.googleusercontent.com/d/1IuDML8VfQ2Vvy5H-xdt_GIvHjxpLTUUx",
            "https://lh3.googleusercontent.com/d/1nNwoqlVVEQ50kW-LpDnwFnikA3dL5MG2",
            "https://lh3.googleusercontent.com/d/1ObPRNespNAnGfalGPmbYgRtTG6Cu05XH",
            "https://lh3.googleusercontent.com/d/1eAiF94iqERaMd_F0imeux7t8QTqHBaYa",
            "https://lh3.googleusercontent.com/d/1fQeSq2Wz-AcQ0F0XEMTWHXEJGFTsONRc",
            "https://lh3.googleusercontent.com/d/1FmkMxB4t5Nr23AWlCwSIRBCZtB984osu",
            "https://lh3.googleusercontent.com/d/16sMhmcTd-2xesK5t5_zve39zbyWcM7I-",
            "https://lh3.googleusercontent.com/d/10gr55uJ135uVM14uoQzVV3lM-pcoYIfT",
            "https://lh3.googleusercontent.com/d/1Jaz17e6liSLC5Y1i3EZTfM0aQZO_6IMe",
            "https://lh3.googleusercontent.com/d/14M2JNSsB9u3qjj7MQb4ZFHn7cWrmZ5wg",
            "https://lh3.googleusercontent.com/d/1WqcNGnc3SExpqdSTaTF4loTK88SO3BDz",
            "https://lh3.googleusercontent.com/d/1raVrNtipi8z7eksQyhE5VCA1bHj57BpP",
            "https://lh3.googleusercontent.com/d/19L_ZkwqrtxGhsrsA0OY81q7ksIS2meY9"
        ],
        "videoUrl": "https://drive.google.com/file/d/1EeCTr-_UWpPbqK3iEHnNBG1B1eY3cD-z/preview",
        "order": 10,
        "ishidden": false,
        "isFeatured": false,
        "frameWidth": "",
        "frameHeight": "",
        "frameGlassEffect": "",
        "frameColor": "",
        "spotlightColor": "",
        "spotlightIntensity": "",
        "frameBorder": "",
        "frameShadow": "",
        "client": "",
        "role": "AI Campaign Visualization",
        "year": "2026",
        "location": "",
        "softwareUsed": "Chat GPT, Google Flow",
        "awards": "",
        "linkInstagram": "",
        "linkBehance": "",
        "linkVideo": "",
        "linkLive": "",
        "linkFigma": "",
        "linkPdf": "",
        "bannerUrl": "https://lh3.googleusercontent.com/d/19-7LmwYRIWgD_-OrJhwlHovYgsS3ZRcL"
    },
    {
        "id": "goldiee-masale",
        "title": "Goldiee Masale",
        "subtitle": "Campaign",
        "tags": "",
        "shortDescription": "Designed print-ready newspaper advertisements published to enhance Goldiee Masale's brand visibility and promotional reach.",
        "about": "Design impactful newspaper advertisements for Goldiee Masale that effectively communicate product offerings, promotional messages, and brand identity while maintaining high print readability and visual appeal.",
        "approach": "",
        "conclusion": "Successfully delivered print-ready newspaper advertisements that were published, enhancing brand visibility and effectively communicating promotional campaigns to a wide audience.",
        "roles": [
            "**Designed visually impactful newspaper advertisements aligned with Goldiee Masale's brand identity and marketing objectives. Prepared print-ready layouts",
            "optimized typography",
            "imagery",
            "and artwork for successful newspaper publication."
        ],
        "ctaLabel": "View Project",
        "ctaHref": "project-detail.html?id=goldiee-masale",
        "bannerImage": "https://lh3.googleusercontent.com/d/1uxxo7EODbwFXR52qL3Iy4eqxKzXAKWPj",
        "images": [
            "https://lh3.googleusercontent.com/d/1TrR2OztcxWPzQNOe2ul73QZidG4DjKmn",
            "https://lh3.googleusercontent.com/d/1ezDaBjeoXFqPLaocBc5ohyPljNFmp7ig",
            "https://lh3.googleusercontent.com/d/1oQDescYr16k2JieB_veMp2VtoS7Y84Lx",
            "https://lh3.googleusercontent.com/d/1RVFgp1rS2uyDKfSP0LIBW_45wEK0ZOyL",
            "https://lh3.googleusercontent.com/d/1dAg_E6iLbSK_xbiE-bQRUKGJCGAxHigW",
            "https://lh3.googleusercontent.com/d/1qJPwY8oVHf03G2YbaJyUJGZr3lRQcvAj",
            "https://lh3.googleusercontent.com/d/1pyNJ0Z6FOHHvgVrUXzdv9rOR308MARd4",
            "https://lh3.googleusercontent.com/d/1krzZJdxpy7AI9UNUsbOa3wKueXkPOqns",
            "https://lh3.googleusercontent.com/d/1QF59cYQNI9E_MGaNhNWW5jc3hGH7mZLe",
            "https://lh3.googleusercontent.com/d/1Kabogf38eyRWdz6s9gLH08obXHkGCssB",
            "https://lh3.googleusercontent.com/d/1FSaAy4lw_ATUDf1S-KyqQXV_ws3Wv3Tx",
            "https://lh3.googleusercontent.com/d/1C7EjqMe8kuy5vq10YCFO82YsGtEnF3s-",
            "https://lh3.googleusercontent.com/d/1GUtpVBc9bzKxtH_1Xg_xyyI5n-BUnDVG",
            "https://lh3.googleusercontent.com/d/1YX7yHPk5TQzDt3DLlWFXFItVxkxmWPgg",
            "https://lh3.googleusercontent.com/d/1CQ8-6gu6SlGzZ32AOe8Dh5BpykW5P1-k",
            "https://lh3.googleusercontent.com/d/1XXcCKXcEU_XZo-6kLhzTpzsctHiaOzT9",
            "https://lh3.googleusercontent.com/d/1uxxo7EODbwFXR52qL3Iy4eqxKzXAKWPj"
        ],
        "videoUrl": "https://drive.google.com/file/d/1ezDaBjeoXFqPLaocBc5ohyPljNFmp7ig/preview",
        "order": 10,
        "ishidden": false,
        "isFeatured": false,
        "frameWidth": "",
        "frameHeight": "",
        "frameGlassEffect": "",
        "frameColor": "",
        "spotlightColor": "",
        "spotlightIntensity": "",
        "frameBorder": "",
        "frameShadow": "",
        "client": "",
        "role": "Graphic Designer",
        "year": "2024",
        "location": "Kanpur",
        "softwareUsed": "coreldraw, Photoshop",
        "awards": "",
        "linkInstagram": "",
        "linkBehance": "",
        "linkVideo": "",
        "linkLive": "",
        "linkFigma": "",
        "linkPdf": "",
        "bannerUrl": "https://lh3.googleusercontent.com/d/1uxxo7EODbwFXR52qL3Iy4eqxKzXAKWPj"
    },
    {
        "id": "gondeshwer-projection-mapping",
        "title": "Gondeshwer Projection Mapping",
        "subtitle": "Projection Mapping & Light Show",
        "tags": "",
        "shortDescription": "Designed immersive projection mapping visuals for the Gondeshwar Temple Light & Sound Show.",
        "about": "Develop immersive projection mapping visuals that bring the history, architecture, and cultural significance of Gondeshwar Temple to life through cinematic storytelling, while ensuring accurate visual alignment with the temple's architectural features for a seamless Light & Sound Show experience.",
        "approach": "",
        "conclusion": "Successfully delivered visually engaging projection mapping content that transformed the temple façade into an immersive storytelling experience, enhancing visitor engagement through a seamless blend of history, architecture, and digital visuals.",
        "roles": [
            "Created high-quality projection mapping visuals aligned with the temple's architecture and historical narrative. Designed cinematic visual sequences",
            "developed creative concepts",
            "and optimized content for large-scale projection."
        ],
        "ctaLabel": "View Project",
        "ctaHref": "project-detail.html?id=gondeshwer-projection-mapping",
        "bannerImage": "https://lh3.googleusercontent.com/d/1sSyCkgqbtY6GFlEYfVQoc5s6KQCsfmQ4",
        "images": [
            "https://lh3.googleusercontent.com/d/1z_EQELpV0mDpwvwgySJYdjfhcxLTG5yR",
            "https://lh3.googleusercontent.com/d/1PuiEPuyQSnKzgy-J-ZitT-P7-zImTadm",
            "https://lh3.googleusercontent.com/d/1zNBEG8XHSl3qqdu23elCW_r65EjuHifG",
            "https://lh3.googleusercontent.com/d/1L25IuiC9JGkYxgW2adlt0luLlMVe_Rbh",
            "https://lh3.googleusercontent.com/d/1uMRpwMPYtqKmztjtkHi6BWSqYT8xq1pS",
            "https://lh3.googleusercontent.com/d/1h-n2xBPSpBiby-CaWQUCXNf2Vai6rwI7",
            "https://lh3.googleusercontent.com/d/1lYdvlmWNeZcdiESdMAIva9PQwfrFOW5w",
            "https://www.youtube.com/embed/LslD70Dk5ik?autoplay=1&mute=1&loop=1&playlist=LslD70Dk5ik&controls=0&showinfo=0&autohide=1&modestbranding=1"
        ],
        "videoUrl": "https://www.youtube.com/embed/b1-sFbeWnWo?autoplay=1&mute=1&loop=1&playlist=b1-sFbeWnWo&controls=0&showinfo=0&autohide=1&modestbranding=1",
        "order": 10,
        "ishidden": false,
        "isFeatured": false,
        "frameWidth": "",
        "frameHeight": "",
        "frameGlassEffect": "",
        "frameColor": "",
        "spotlightColor": "",
        "spotlightIntensity": "",
        "frameBorder": "",
        "frameShadow": "",
        "client": "",
        "role": "Scene Design Visual Storytelling",
        "year": "2025",
        "location": "",
        "softwareUsed": "Photoshop",
        "awards": "",
        "linkInstagram": "",
        "linkBehance": "",
        "linkVideo": "",
        "linkLive": "",
        "linkFigma": "",
        "linkPdf": "",
        "bannerUrl": "https://lh3.googleusercontent.com/d/1sSyCkgqbtY6GFlEYfVQoc5s6KQCsfmQ4"
    },
    {
        "id": "iccs-museum",
        "title": "ICCS Museum",
        "subtitle": "Museum",
        "tags": "",
        "shortDescription": "Designed exhibition graphics that enhanced storytelling and visitor engagement for the ICCS Museum.",
        "about": "Design engaging museum graphics that effectively communicate the vision, achievements, and key narratives of ICCS through clear visual storytelling and a cohesive exhibition experience.",
        "approach": "",
        "conclusion": "Successfully delivered a cohesive set of museum graphics that strengthened the exhibition's visual identity, improved information accessibility, and created an engaging and memorable visitor experience.",
        "roles": [
            "Designed exhibition graphics",
            "information panels",
            "infographics",
            "wall graphics",
            "and print-ready visual assets aligned with the museum's narrative."
        ],
        "ctaLabel": "View Project",
        "ctaHref": "project-detail.html?id=iccs-museum",
        "bannerImage": "https://lh3.googleusercontent.com/d/147aOVSWY1rhmxYiVg4oRxeo_yFFMXSJ-",
        "images": [
            "https://lh3.googleusercontent.com/d/1tmCTgtKIJNs1mDJ89piL4s14Kz68O_jN",
            "https://lh3.googleusercontent.com/d/1bjtaRz3CufB2Qgey87tktbi2MMmjqXOD",
            "https://lh3.googleusercontent.com/d/1yrePEh-ClTAxmiYDjbv6Bk7kSmJ3k7g4",
            "https://lh3.googleusercontent.com/d/1U6BYpOBOP6KikUR3SXGSSS0YMLxiycaJ",
            "https://lh3.googleusercontent.com/d/1RaacQ1KWTppWwGrtAD4PqvuGl5-tt5wM",
            "https://lh3.googleusercontent.com/d/1aSAKEz7iLX0GTh6jNDwMpgxYB35a0nHL",
            "https://lh3.googleusercontent.com/d/1jOFocBWAWeGJMLsCvCvUo3fxWgs1bY7F",
            "https://lh3.googleusercontent.com/d/16C1v7f_nZ1KoEQNdYJYlaZbozUBQh5mq",
            "https://lh3.googleusercontent.com/d/1tsUUFrou6en0Dx5OkoMFGYl7i3jW8cwG",
            "https://lh3.googleusercontent.com/d/1Hn2gp-cq474v8N4u-rrLRZt3OPZpQwrj",
            "https://lh3.googleusercontent.com/d/15Xfm6w2h-RRB0v6gQHunk3H0fNEJO6uU",
            "https://lh3.googleusercontent.com/d/1EFD6TZtRWm2uVvoYaAq8nCLTlx7qUqFT",
            "https://lh3.googleusercontent.com/d/1cNvyDjA4WHZtGOwAsHYa5Ac-8VNpiW5b",
            "https://lh3.googleusercontent.com/d/116ew6fZt5zAOn8IIIozSdZfj22NG83IG"
        ],
        "videoUrl": "https://www.youtube.com/embed/hfGCA4Xr2fI?autoplay=1&mute=1&loop=1&playlist=hfGCA4Xr2fI&controls=0&showinfo=0&autohide=1&modestbranding=1",
        "order": 10,
        "ishidden": false,
        "isFeatured": false,
        "frameWidth": "",
        "frameHeight": "",
        "frameGlassEffect": "",
        "frameColor": "",
        "spotlightColor": "",
        "spotlightIntensity": "",
        "frameBorder": "",
        "frameShadow": "",
        "client": "",
        "role": "Museum Graphic Designer",
        "year": "2025",
        "location": "Delhi",
        "softwareUsed": "Photoshop",
        "awards": "",
        "linkInstagram": "",
        "linkBehance": "",
        "linkVideo": "",
        "linkLive": "",
        "linkFigma": "",
        "linkPdf": "",
        "bannerUrl": "https://lh3.googleusercontent.com/d/147aOVSWY1rhmxYiVg4oRxeo_yFFMXSJ-"
    },
    {
        "id": "kapila-milkomore",
        "title": "Kapila Milkomore",
        "subtitle": "Campaign",
        "tags": "",
        "shortDescription": "Designed newspaper ads, promotional banners, and TV L-band creatives for Kapila Milkomore.",
        "about": "Design impactful advertising creatives for Kapila Milkomore across newspaper, banners, and TV L-band formats while maintaining a consistent brand identity, strong product visibility, and effective marketing communication.",
        "approach": "",
        "conclusion": "Successfully delivered high-quality advertising creatives across multiple media formats, strengthening brand visibility, ensuring consistent communication, and supporting effective promotional campaigns.",
        "roles": [
            "Designed newspaper advertisements",
            "promotional banners",
            "and TV L-band creatives aligned with the brand's marketing campaigns."
        ],
        "ctaLabel": "View Project",
        "ctaHref": "project-detail.html?id=kapila-milkomore",
        "bannerImage": "https://lh3.googleusercontent.com/d/1R0kZL4xNg3y24sTR8XUfmdOOr26e3_RI",
        "images": [
            "https://lh3.googleusercontent.com/d/1Jpg1rn88gtrq5ZfQFiTleVrF3h43g2hS",
            "https://lh3.googleusercontent.com/d/1euiqwTYY82XMDgKSu7KxzdcYrxf6VlJ3",
            "https://lh3.googleusercontent.com/d/1uoLZmeNPyiAAsWtOWyQst2m-vm8xq3oG",
            "https://lh3.googleusercontent.com/d/1tlLQfpw1_39ZVOjbSj1FbAXYVCvV7_jf",
            "https://lh3.googleusercontent.com/d/1earefR7m1BUR8Ze2L7a2-03SgjV-PhU1",
            "https://lh3.googleusercontent.com/d/1c28pslndwYCh2vCjtelPMjksF_6mk_hS",
            "https://lh3.googleusercontent.com/d/1ZVbq95b93frXImnMjaORpABUEDhatOhW"
        ],
        "videoUrl": "https://drive.google.com/file/d/1R0kZL4xNg3y24sTR8XUfmdOOr26e3_RI/preview",
        "order": 10,
        "ishidden": false,
        "isFeatured": false,
        "frameWidth": "",
        "frameHeight": "",
        "frameGlassEffect": "",
        "frameColor": "",
        "spotlightColor": "",
        "spotlightIntensity": "",
        "frameBorder": "",
        "frameShadow": "",
        "client": "",
        "role": "Graphic Designer",
        "year": "2024",
        "location": "Kanpur",
        "softwareUsed": "Photoshop, coreldraw",
        "awards": "",
        "linkInstagram": "",
        "linkBehance": "",
        "linkVideo": "",
        "linkLive": "",
        "linkFigma": "",
        "linkPdf": "",
        "bannerUrl": "https://lh3.googleusercontent.com/d/1R0kZL4xNg3y24sTR8XUfmdOOr26e3_RI"
    },
    {
        "id": "national-archive-museum",
        "title": "National Archive Museum",
        "subtitle": "Museum",
        "tags": "",
        "shortDescription": "Designed museum graphics showcasing India's archival heritage through engaging visual storytelling.",
        "about": "Design engaging museum graphics that preserve and present India's archival heritage through clear visual communication, informative exhibition content, and an immersive visitor experience.",
        "approach": "",
        "conclusion": "Successfully delivered a cohesive visual communication system that enhanced archival storytelling, improved visitor engagement, and strengthened the museum's exhibition experience through well-structured graphics.",
        "roles": [
            "Designed exhibition graphics",
            "archival information panels",
            "infographics",
            "wall graphics",
            "and print-ready visual assets aligned with the museum's narrative."
        ],
        "ctaLabel": "View Project",
        "ctaHref": "project-detail.html?id=national-archive-museum",
        "bannerImage": "https://lh3.googleusercontent.com/d/187x0rSILpLBofCeLWrvjEu6DlZilDALU",
        "images": [
            "https://lh3.googleusercontent.com/d/1HK3YYESnfghyyPiYxxkrY7i3nyWJ68Jt",
            "https://lh3.googleusercontent.com/d/1NfwEPT4TnYiKWxYo7XDMyr0dwfA8j_a1",
            "https://lh3.googleusercontent.com/d/1GN4LCaQlEBKhhnI1n9CTGAdLNY8twTuu",
            "https://lh3.googleusercontent.com/d/1DmTzhDmIla4LPnSlyPZ28gMJdbuyrRH8",
            "https://lh3.googleusercontent.com/d/1c-BiGToT31W438V_6Z_QWhDgR-sltt5N",
            "https://lh3.googleusercontent.com/d/1oRCF3GgZNotteFAoLylMOkq4-6Bag5cM",
            "https://lh3.googleusercontent.com/d/1CqIxEDB7LaxLMyrBOOvP0btQWiYAgisb",
            "https://lh3.googleusercontent.com/d/1754SpYO9N38vzImaM5_hngVO_t_XMhv-",
            "https://lh3.googleusercontent.com/d/1m60saFEGAx5EIxFwhNBdWft99IU7lyr4",
            "https://lh3.googleusercontent.com/d/1398eVsvoArs4o-jkGO3gf6ELe4Btanuc",
            "https://lh3.googleusercontent.com/d/1AYuqRPbgCcyg6uu4g0y3lxy42NR9Vo_k",
            "https://lh3.googleusercontent.com/d/1AxRF462ZQ5mPdmW7h70_Rk50Rc6PSInW",
            "https://lh3.googleusercontent.com/d/1dV7Py3DElKYDqgwBqgfzrgKl58H2zC0Y",
            "https://lh3.googleusercontent.com/d/1v_RclYN7AQ9e4ZzswfLtCRWr2dOLhW_P",
            "https://lh3.googleusercontent.com/d/1ufQmXPa45jZHV8fyAsiyF0Xn0grJHEnS",
            "https://lh3.googleusercontent.com/d/1vrLzdQxal3G6mKgVkg8irPo6-21nPEDL",
            "https://lh3.googleusercontent.com/d/1cbZHNfcJOsWCjZ7DfgZsWTPKDqKlh5bJ",
            "https://lh3.googleusercontent.com/d/1gDrabzx1dDCbm0VZEb-Jfdcl-LFFASr7",
            "https://lh3.googleusercontent.com/d/1N4wRBDZgTgAsDwAfMkpymiSCytpsCJVU",
            "https://lh3.googleusercontent.com/d/1yALoYTwNpVx4ACtaiHLW0_K7oEWhnwwd"
        ],
        "videoUrl": "https://www.youtube.com/embed/D8_nGefrpw0?autoplay=1&mute=1&loop=1&playlist=D8_nGefrpw0&controls=0&showinfo=0&autohide=1&modestbranding=1",
        "order": 10,
        "ishidden": false,
        "isFeatured": false,
        "frameWidth": "",
        "frameHeight": "",
        "frameGlassEffect": "",
        "frameColor": "",
        "spotlightColor": "",
        "spotlightIntensity": "",
        "frameBorder": "",
        "frameShadow": "",
        "client": "",
        "role": "Museum Graphic Designer",
        "year": "2025",
        "location": "Delhi",
        "softwareUsed": "Photoshop",
        "awards": "",
        "linkInstagram": "",
        "linkBehance": "",
        "linkVideo": "",
        "linkLive": "",
        "linkFigma": "",
        "linkPdf": "",
        "bannerUrl": "https://lh3.googleusercontent.com/d/187x0rSILpLBofCeLWrvjEu6DlZilDALU"
    },
    {
        "id": "nausena-museum",
        "title": "Nausena Museum",
        "subtitle": "Museum",
        "tags": "",
        "shortDescription": "Designed museum graphics showcasing the legacy and achievements of the Indian Navy.",
        "about": "Design engaging museum graphics that effectively communicate the heritage, achievements, and operational excellence of the Indian Navy through clear visual storytelling and immersive exhibition experiences.",
        "approach": "",
        "conclusion": "Successfully delivered a cohesive set of museum graphics that enhanced the visitor experience, strengthened visual storytelling, and effectively communicated the Indian Navy's history and achievements through engaging exhibition design.",
        "roles": [
            "Designed exhibition graphics",
            "information panels",
            "infographics",
            "and environmental graphics aligned with the museum's narrative. Developed visually consistent layouts",
            "artwork",
            "and print-ready assets to enhance visitor engagement and exhibition communication."
        ],
        "ctaLabel": "View Project",
        "ctaHref": "project-detail.html?id=nausena-museum",
        "bannerImage": "https://lh3.googleusercontent.com/d/1P3GsdBd-3HN2HaT8cpYK5LmJ8jyrimRv",
        "images": [
            "https://lh3.googleusercontent.com/d/1_9L2KcqPFpBsq_z-WxJtMTqJ2p8Ix1DP",
            "https://lh3.googleusercontent.com/d/1iDjYZDm0hBtFkGE8mtMKL-FWagrFCE0G",
            "https://lh3.googleusercontent.com/d/1ygYreh-ErfoMyHSP0ButJRMk3E1gci6W",
            "https://lh3.googleusercontent.com/d/1mDXGCtR1fnAuoUiiiuhYXRWia5u_7FFm",
            "https://lh3.googleusercontent.com/d/1Jumkjb3liY_zBjiJjsh6cmslX5QRI6N7",
            "https://lh3.googleusercontent.com/d/1GwPBYgRGXt6bwoPBaQwQJb7ha-6tHzFI",
            "https://lh3.googleusercontent.com/d/1ZnpM_oxyo0j6n0ro4kvN4DGNz92vC6h6",
            "https://lh3.googleusercontent.com/d/1tnoEwIUuyMlPEQI_kojF7dOJNiTJ71ul",
            "https://lh3.googleusercontent.com/d/1ycBZN1xFZK9R5YpElVnR5bBW9JyxG02B",
            "https://lh3.googleusercontent.com/d/1Jeck_j5l57qgd4iSXnm2KB713cM3KSCk",
            "https://lh3.googleusercontent.com/d/1KT2Uv0DtAyhk8k95tuCkYMgYFXb5uUkd",
            "https://lh3.googleusercontent.com/d/1lWpN8G1ZTyQzhRkESQ4Q3uimDsMrIUmo",
            "https://lh3.googleusercontent.com/d/1SS1q1V0UBZNxU65ZJEhMqslGpB1mYO7p",
            "https://lh3.googleusercontent.com/d/1GFyVGp3WSyonJPlUqnAIgc3p-YvCG-HQ",
            "https://lh3.googleusercontent.com/d/168ELQCuO2Oav9CqHGYgw_IM5bdHqE7YC",
            "https://lh3.googleusercontent.com/d/1cEse3ISVNjhBYAih8Vz_7lGvWh-f4dYg",
            "https://lh3.googleusercontent.com/d/19RmiX2hKnc9Jbyq0X9mb96PmG7kNqqFF",
            "https://lh3.googleusercontent.com/d/1kBB8Nwt6Gch5sIGca7zGCd_zHaWtrYhH",
            "https://lh3.googleusercontent.com/d/1I2pGaon3TLHIdjIWgl_SJvWjH3VfEcLn",
            "https://lh3.googleusercontent.com/d/1LdQ9tBickiFX3tdJXjuVe4EJJpjF2c4a",
            "https://lh3.googleusercontent.com/d/12hX0PoI64ackMebQRan8CjwMA6muPwmK",
            "https://lh3.googleusercontent.com/d/1C9nRHMJDJFIliIlimU6hPsSPdS4yXXvM",
            "https://lh3.googleusercontent.com/d/1PIgnki4Eid3AljlOHVS8PHa3l__xRS6N",
            "https://lh3.googleusercontent.com/d/1bsOsSb-Mz0J3gmNZtrsMBaOFoIkkGAnh",
            "https://lh3.googleusercontent.com/d/1zlYfUhLU-NGRh7nBLG7FG9zQPsfPROlg"
        ],
        "videoUrl": "https://www.youtube.com/embed/qv0QWzI00UI?autoplay=1&mute=1&loop=1&playlist=qv0QWzI00UI&controls=0&showinfo=0&autohide=1&modestbranding=1",
        "order": 8,
        "ishidden": false,
        "isFeatured": true,
        "frameWidth": "",
        "frameHeight": "",
        "frameGlassEffect": "",
        "frameColor": "",
        "spotlightColor": "",
        "spotlightIntensity": "",
        "frameBorder": "",
        "frameShadow": "",
        "client": "",
        "role": "Museum Graphic Designer",
        "year": "2025-2026",
        "location": "Delhi",
        "softwareUsed": "Photoshop",
        "awards": "",
        "linkInstagram": "",
        "linkBehance": "",
        "linkVideo": "",
        "linkLive": "",
        "linkFigma": "",
        "linkPdf": "",
        "bannerUrl": "https://lh3.googleusercontent.com/d/1P3GsdBd-3HN2HaT8cpYK5LmJ8jyrimRv"
    },
    {
        "id": "ncert-museum",
        "title": "NCERT Museum",
        "subtitle": "MUSEUM",
        "tags": "",
        "shortDescription": "An interactive educational pavilion utilizing immersive projection and modular layouts.",
        "about": "Designing a modern pavilion for students and educators that presents national curricula through physical interaction, projection spaces, and bold typographic graphic panels.",
        "approach": "",
        "conclusion": "",
        "roles": [
            "Environmental Graphic Designer",
            "Projection Concept Artist",
            "Layout Specialist"
        ],
        "ctaLabel": "View Project",
        "ctaHref": "project-detail.html?id=ncert-museum",
        "bannerImage": "https://lh3.googleusercontent.com/d/1XfKAs0kLkBvpKpzTe8qNyzaj4J-t9dZQ",
        "images": [
            "https://lh3.googleusercontent.com/d/1HbQv8doEZ2rMse-DVN-9m5Wl3Yqx8d6Q",
            "https://lh3.googleusercontent.com/d/16yPv5f29MDUvB1YZWj7-vP_tAja1Kq_B",
            "https://lh3.googleusercontent.com/d/1laczDxvFtApYvjxh_JAQJfX8NEvyaUDw",
            "https://lh3.googleusercontent.com/d/1Aobm71AFDKLt2RtyVzw5cWW1EsO9grpd",
            "https://lh3.googleusercontent.com/d/10jHl6SlqR4Uf-_RB3nMgvPWprlKx7TQ3",
            "https://lh3.googleusercontent.com/d/1LAG6ByBKdYLGJ6cxQZS5NOdx19YclqHN",
            "https://lh3.googleusercontent.com/d/1TIDZAvw11ECt1BIbw4ijUlGRVhukpXlk",
            "https://lh3.googleusercontent.com/d/1VXj3TV4mY4pgN0LdojEAYtRQAfBKD0kk",
            "https://lh3.googleusercontent.com/d/1d6E43Cyxx5rGfv5NZy2qSgqWZDmuGiJg",
            "https://lh3.googleusercontent.com/d/1crOwRCzIIkjha2PFN5iJDkPsZoC88Vsf",
            "https://lh3.googleusercontent.com/d/1GjwF2HXQOVFc4aZuEMW5LDncmsKywmhZ",
            "https://lh3.googleusercontent.com/d/1KJcbCFCRSK_itz6QQnE5ucplOVt7GqpJ",
            "https://lh3.googleusercontent.com/d/1prFvTgP5iieJj0dJ-3bPhq7ir54107F2",
            "https://lh3.googleusercontent.com/d/1dXhimFhL4blCx5_xKizIjZMRd-zWakUh"
        ],
        "videoUrl": "https://www.youtube.com/embed/2gcqv5PhJ4A?autoplay=1&mute=1&loop=1&playlist=2gcqv5PhJ4A&controls=0&showinfo=0&autohide=1&modestbranding=1",
        "order": 3,
        "ishidden": false,
        "isFeatured": true,
        "frameWidth": "",
        "frameHeight": "",
        "frameGlassEffect": "",
        "frameColor": "",
        "spotlightColor": "",
        "spotlightIntensity": "",
        "frameBorder": "",
        "frameShadow": "",
        "client": "",
        "role": "",
        "year": "2025",
        "location": "Delhi",
        "softwareUsed": "PHOTOSHOP",
        "awards": "",
        "linkInstagram": "",
        "linkBehance": "",
        "linkVideo": "",
        "linkLive": "",
        "linkFigma": "",
        "linkPdf": "",
        "bannerUrl": "https://lh3.googleusercontent.com/d/1XfKAs0kLkBvpKpzTe8qNyzaj4J-t9dZQ"
    },
    {
        "id": "nike-own-your-speed",
        "title": "Nike Own your Speed",
        "subtitle": "Campaign Design & AI Visual Art",
        "tags": "",
        "shortDescription": "AI-integrated concept advertising campaign reimagining sustainable performance footwear.",
        "about": "Create a high-impact AI advertising campaign that captures Nike's spirit of speed, performance, and innovation through cinematic visuals while maintaining a bold, premium, and athlete-focused brand identity.",
        "approach": "",
        "conclusion": "Delivered a visually compelling AI campaign that reinforced Nike's performance-driven identity through dynamic storytelling, premium product visualization, and high-impact commercial imagery suitable for digital marketing and brand promotions.",
        "roles": [
            "Developed creative concepts and AI-generated campaign visuals aligned with Nike's premium brand identity. Designed cinematic product-focused compositions",
            "lifestyle imagery",
            "and commercial-ready advertising creatives."
        ],
        "ctaLabel": "View Project",
        "ctaHref": "project-detail.html?id=nike-own-your-speed",
        "bannerImage": "https://lh3.googleusercontent.com/d/1AYlAKXpXTov2MOo-KeCJ4Mgl4HceRWWl",
        "images": [
            "https://lh3.googleusercontent.com/d/1dAlyT_HC6G8KGhmadec1KwlewJsDy_ev",
            "https://lh3.googleusercontent.com/d/1BdKzX8s5gh0r1w4q4Q_o4jBNsBloqx_D",
            "https://lh3.googleusercontent.com/d/1JDHnsepu9jQgWsL7jQNXRmAeVvBsrOSH",
            "https://lh3.googleusercontent.com/d/1fYp_g9vtN4zUSARbGyc5-Q3lWUpgJtXB",
            "https://lh3.googleusercontent.com/d/1eYtjQTG3ZsATtkNA91Og0u6Xc5FHL-9k",
            "https://lh3.googleusercontent.com/d/1Z3g09MAOcSiFOdjn0WByvcwKJJpPMVMo",
            "https://lh3.googleusercontent.com/d/1ulbgtdYuPYaG50NXmTC0sxlRxK3lyeRD",
            "https://lh3.googleusercontent.com/d/19ZbbIOsuk4WdAamgaze240fyh0zZk7Y8",
            "https://lh3.googleusercontent.com/d/1CDGbDktdn-3VTAnQws1xde4T3v6Pcos7",
            "https://lh3.googleusercontent.com/d/10214KnuemEShL16TARakpZUgp2AhQES0",
            "https://lh3.googleusercontent.com/d/1R0OAFkurcFwEfF29MMyD8549Gq9NE7nH",
            "https://lh3.googleusercontent.com/d/1PG9KNBM7fB6mfvwNQBmtkTSGvAU3XzOj",
            "https://lh3.googleusercontent.com/d/1yxcnk4sNsFoz3QkpK1hzS02oOM8-zxZ-",
            "https://lh3.googleusercontent.com/d/1TpE8KMbngj0VgtOgH0gnsM2MMc9huVaw",
            "https://lh3.googleusercontent.com/d/1ltXS0Rc5eEYPUNPHmLmqMiDJvC7pzMoa",
            "https://lh3.googleusercontent.com/d/1Ve-uw1QjTJNKbLuUSrHbAXX28vC4DvDh",
            "https://lh3.googleusercontent.com/d/1ACWpgzQPS2zEs5P3vaYeCQbyTPTigH78",
            "https://lh3.googleusercontent.com/d/1s95EDwTxj5wqW3NTG1kh6EL6EdRL8ofC",
            "https://lh3.googleusercontent.com/d/10G6P7A-S0cE3OAVo8zVsphocZE5k0jwf",
            "https://lh3.googleusercontent.com/d/1b-HeFoyuOn_vajIaFIS-9klT9lR6f_ne",
            "https://lh3.googleusercontent.com/d/1SCZJF0smFl_fyNU82WiHbWLsybq4MPqD",
            "https://lh3.googleusercontent.com/d/1zeldtpG4blZLoGE-2mS_9twyj4dtCLK9",
            "https://lh3.googleusercontent.com/d/1PtPpn-DeSH4YUDN1zBuBmrp2vAc2owzS",
            "https://lh3.googleusercontent.com/d/1WbBOoan6fNjxT3awuozvcfbFVNL7pwC5",
            "https://lh3.googleusercontent.com/d/1XQhQ_a2m2t-YBAmxjzaYhp6LB3EMjFQe"
        ],
        "videoUrl": "https://www.youtube.com/embed/RiMxFoMDYD4?autoplay=1&mute=1&loop=1&playlist=RiMxFoMDYD4&controls=0&showinfo=0&autohide=1&modestbranding=1",
        "order": 5,
        "ishidden": false,
        "isFeatured": false,
        "frameWidth": "",
        "frameHeight": "",
        "frameGlassEffect": "",
        "frameColor": "",
        "spotlightColor": "",
        "spotlightIntensity": "",
        "frameBorder": "",
        "frameShadow": "",
        "client": "",
        "role": "AI Campaign Visualization",
        "year": "2026",
        "location": "",
        "softwareUsed": "Google Flow, Chat GPT",
        "awards": "",
        "linkInstagram": "",
        "linkBehance": "",
        "linkVideo": "",
        "linkLive": "",
        "linkFigma": "",
        "linkPdf": "",
        "bannerUrl": "https://lh3.googleusercontent.com/d/1AYlAKXpXTov2MOo-KeCJ4Mgl4HceRWWl"
    },
    {
        "id": "nimhans-brain-and-mind-museum",
        "title": "NIMHANS Brain And Mind Museum",
        "subtitle": "Museum",
        "tags": "",
        "shortDescription": "Designed immersive museum graphics that bring brain science and mental health concepts to life.",
        "about": "Design engaging museum graphics that simplify complex neuroscience concepts through clear visual communication, interactive storytelling, and an educational visitor experience.",
        "approach": "",
        "conclusion": "Successfully delivered a cohesive visual communication system that enhanced scientific storytelling, improved visitor understanding, and created an engaging, educational museum experience through impactful exhibition graphics.",
        "roles": [
            "Designed exhibition graphics",
            "information panels",
            "infographics",
            "wall graphics",
            "and print-ready visual assets aligned with the museum's educational narrative."
        ],
        "ctaLabel": "View Project",
        "ctaHref": "project-detail.html?id=nimhans-brain-and-mind-museum",
        "bannerImage": "https://lh3.googleusercontent.com/d/1UDUZ17SScOrGIf-DyDlIzCTUA3IyKgAf",
        "images": [
            "https://lh3.googleusercontent.com/d/17mYpguxWDk5a2IT2-B9L_Y-kfKcy0oFT",
            "https://lh3.googleusercontent.com/d/1zte_c_2IOy_W70hukRTqgWQdjynmXA2H",
            "https://lh3.googleusercontent.com/d/1Z2wbTptWfgusbhaQUE7bZM6ey7_F7a30",
            "https://lh3.googleusercontent.com/d/12wtLs7Xl-cLMO1gIKuXybfAsrGfckons",
            "https://lh3.googleusercontent.com/d/1jnu2o0OHyHCPoPbOxQ1Am3iu2oMtA3Ac",
            "https://lh3.googleusercontent.com/d/1_5AP0ARa3jjjZVEzL0u0o3mI53PE1mNw",
            "https://lh3.googleusercontent.com/d/1cvn5KPOfVO21nungQ1Ffht12MgGgQt_S",
            "https://lh3.googleusercontent.com/d/1aGzCipoqjf_KqCfvyn0sRZ0vAOc0d3is",
            "https://lh3.googleusercontent.com/d/1WNU5WW4VNLBdOvA3EuRnFDDSN15KYK9N",
            "https://lh3.googleusercontent.com/d/1cVeWF7opXInot_8hmoSvB_QrwvVrZmxM",
            "https://lh3.googleusercontent.com/d/1vY3aE_n_wgglFEkm_Tpbzv3oESvSqNHU",
            "https://lh3.googleusercontent.com/d/1HUS1jFUblTEpTiOKjszg3iJ5jwsNVK-U",
            "https://lh3.googleusercontent.com/d/1JNMkX1McAnfdRA9XQK2mqicUDAEg5__D",
            "https://lh3.googleusercontent.com/d/1_EcI3rEdPzihE5Yq0AwpXfDX1sXdiSty",
            "https://lh3.googleusercontent.com/d/1tFO4JaO0Brg9WsSeU947OfDhJ1eBnifD",
            "https://lh3.googleusercontent.com/d/10jejGff3svUB8HOtnlfm7jYMHnKLznno",
            "https://lh3.googleusercontent.com/d/1uFxcnyeX_mJFRpgm_Oa8rnVt5tZH-jcX",
            "https://lh3.googleusercontent.com/d/1Y-vev4TFAsktnGpnGA7jB4M16pYXEv5G",
            "https://lh3.googleusercontent.com/d/1OdEw6SG-lxRh78CHCkiSa2UvBmQLQNSq",
            "https://lh3.googleusercontent.com/d/1XAxa36gX0NcigxZ8iRctYYXszAYBfGIN",
            "https://lh3.googleusercontent.com/d/10Jnr4F91s7mocQTFbemneKjdL_RcA9NI",
            "https://lh3.googleusercontent.com/d/109817NMgXm8xddvHGFBwasmOqagKCzct",
            "https://lh3.googleusercontent.com/d/1-gqJO982jDk2Q3GgX4sVKlPraEePl0GD",
            "https://lh3.googleusercontent.com/d/15FAj29uWPsKvOLrJEYU1hZ4ff-BsRcpx",
            "https://lh3.googleusercontent.com/d/1jesPotiQQzXh481JrWIVm9bdQRMXjSW_"
        ],
        "videoUrl": "https://www.youtube.com/embed/2_oMYlCv6TY?autoplay=1&mute=1&loop=1&playlist=2_oMYlCv6TY&controls=0&showinfo=0&autohide=1&modestbranding=1",
        "order": 12,
        "ishidden": false,
        "isFeatured": true,
        "frameWidth": "",
        "frameHeight": "",
        "frameGlassEffect": "",
        "frameColor": "",
        "spotlightColor": "",
        "spotlightIntensity": "",
        "frameBorder": "",
        "frameShadow": "",
        "client": "",
        "role": "Museum Graphic Designer",
        "year": "2025-2026",
        "location": "Bengaluru",
        "softwareUsed": "Photoshop",
        "awards": "",
        "linkInstagram": "",
        "linkBehance": "",
        "linkVideo": "",
        "linkLive": "",
        "linkFigma": "",
        "linkPdf": "",
        "bannerUrl": "https://lh3.googleusercontent.com/d/1UDUZ17SScOrGIf-DyDlIzCTUA3IyKgAf"
    },
    {
        "id": "ravidas-museum",
        "title": "Ravidas Museum",
        "subtitle": "Museum",
        "tags": "",
        "shortDescription": "Led the complete visual design, projection mapping, and AI-powered multimedia content for the Ravidas Museum.",
        "about": "Lead the complete visual design process from concept development to final execution, creating immersive museum graphics, projection mapping content, and AI-powered visual experiences that authentically present the life, teachings, and legacy of Sant Ravidas through engaging storytelling.",
        "approach": "",
        "conclusion": "Successfully delivered a fully integrated museum experience by combining exhibition graphics, projection mapping, and AI-generated multimedia content into a cohesive visual narrative that enhanced visitor engagement, strengthened storytelling, and supported seamless project execution from concept to installation.",
        "roles": [
            "Managed end-to-end visual design",
            "including concept development",
            "exhibition graphics",
            "projection mapping",
            "AI-generated visuals",
            "video content creation",
            "production artwork",
            "and on-site execution."
        ],
        "ctaLabel": "View Project",
        "ctaHref": "project-detail.html?id=ravidas-museum",
        "bannerImage": "https://lh3.googleusercontent.com/d/1Z1eF2GTe6agG7_huEOf2QOy4yuCUK0Z2",
        "images": [
            "https://lh3.googleusercontent.com/d/1rXwaj_cSrYc2gCuBHhhPVjHRDssJe97Q",
            "https://lh3.googleusercontent.com/d/1-CF5yI4s5tmIcbmev3Da7wGn4furhJ3J",
            "https://lh3.googleusercontent.com/d/11zlNH4wyt3nJqRAL1c-nz-v-43r-XK1m",
            "https://lh3.googleusercontent.com/d/1lGAfkS4ywKI7lFMSssN72pC6Mwrada2F",
            "https://lh3.googleusercontent.com/d/1Lg_kqi_BuHMOZfk7jL0sbCLn3YEQOyEn",
            "https://lh3.googleusercontent.com/d/1q9zg_T9c0eUerf-Luocfk7XUx7QdHjpJ",
            "https://lh3.googleusercontent.com/d/1U2zref9fCh_skmvhiRO2_4czOt1wxpap",
            "https://lh3.googleusercontent.com/d/1AC_lRUHz0CqpKqufjPCn02z5BNCx3w-t",
            "https://lh3.googleusercontent.com/d/1Usy_yMWI1a3Ml2XqZ7Ruq9w_iCds70AJ",
            "https://lh3.googleusercontent.com/d/1NMN8ICjphW4E82E1eXnLh_ckW0CKUjoT",
            "https://lh3.googleusercontent.com/d/1BNIh4U8UeTOciRGKIBeL6WOyuItdim-q",
            "https://lh3.googleusercontent.com/d/1QktgrvySZy4NncS22x5O-P_3bGEm1lvz",
            "https://lh3.googleusercontent.com/d/1iJU3S6GpIp9kJxvkgvBZbLTxNmLsNQwx",
            "https://lh3.googleusercontent.com/d/1WinJWt8ogNy3JnTCInqwXD8S-DHpOQPl",
            "https://lh3.googleusercontent.com/d/18eOF1zte11PXa7sBCRVaZDftR-ODlnWr",
            "https://lh3.googleusercontent.com/d/1UKQRw9lNNGgPQCxXO1hlZImBxtG9oGDY",
            "https://lh3.googleusercontent.com/d/1wYvrnVyo97Co9WX1pxpogtnK5GvSvDE-",
            "https://lh3.googleusercontent.com/d/18tcs9e-MqvE6SYNvOojq_aWJ-yb32kW1",
            "https://lh3.googleusercontent.com/d/1YXYSxUmNyBDWwAnqwg1Q9p1ve7aGmncD",
            "https://lh3.googleusercontent.com/d/1V5IMbWThLxkdI39v9_uur8fSa_kY0dLJ",
            "https://lh3.googleusercontent.com/d/1s_CGou1mIJxStnCTWjNyOtkC7-Eo37qg",
            "https://lh3.googleusercontent.com/d/1HG9d2RwAWwrkjm-RVhcZ_KabBPWK1i59",
            "https://lh3.googleusercontent.com/d/1hRd3Hyg_Q4BrQIQstNiQ6cQZLNs1i8PK",
            "https://lh3.googleusercontent.com/d/1vXS_Fc7gjBt4yQs5o67LFIYMVIeqTbj3",
            "https://lh3.googleusercontent.com/d/1PBehgnJQxLqzu44bW3tROiZNOg2bEc07"
        ],
        "videoUrl": "https://www.youtube.com/embed/zWj6ldo2BJA?autoplay=1&mute=1&loop=1&playlist=zWj6ldo2BJA&controls=0&showinfo=0&autohide=1&modestbranding=1",
        "order": 10,
        "ishidden": false,
        "isFeatured": false,
        "frameWidth": "",
        "frameHeight": "",
        "frameGlassEffect": "",
        "frameColor": "",
        "spotlightColor": "",
        "spotlightIntensity": "",
        "frameBorder": "",
        "frameShadow": "",
        "client": "",
        "role": "Lead Museum Graphic Designer & Projection Mapping Visualizer",
        "year": "2025-2026",
        "location": "Delhi",
        "softwareUsed": "Photoshop, coreldraw, Chat Gpt, Magnific, gemini",
        "awards": "",
        "linkInstagram": "",
        "linkBehance": "",
        "linkVideo": "",
        "linkLive": "",
        "linkFigma": "",
        "linkPdf": "",
        "bannerUrl": "https://lh3.googleusercontent.com/d/1Z1eF2GTe6agG7_huEOf2QOy4yuCUK0Z2"
    },
    {
        "id": "reliance-experience-centre",
        "title": "Reliance Experience Centre",
        "subtitle": "Corporate Experience & Interaction",
        "tags": "",
        "shortDescription": "Designed immersive graphics for the Reliance Experience Centre to enhance visitor engagement.",
        "about": "Design engaging graphics that communicate Reliance's innovations, services, and brand vision through immersive visual storytelling, intuitive information design, and a modern experience centre environment.",
        "approach": "",
        "conclusion": "Successfully delivered a cohesive visual communication system that strengthened the experience centre's brand identity, improved visitor interaction, and transformed complex information into engaging, easy-to-understand visual experiences.",
        "roles": [
            "Designed exhibition graphics",
            "information panels",
            "wall graphics",
            "infographics",
            "branding elements",
            "and print-ready visual assets for the experience centre."
        ],
        "ctaLabel": "View Project",
        "ctaHref": "project-detail.html?id=reliance-experience-centre",
        "bannerImage": "https://lh3.googleusercontent.com/d/1OWlikGqUz0E7O8nJqxMLtUKuHwwatmYs",
        "images": [
            "https://lh3.googleusercontent.com/d/1g4X9eqQEpuOEXoeSylEJH4uokcrShp9o",
            "https://lh3.googleusercontent.com/d/14iTLY3YgsH2U6KchoId2Ut2dPEjpGTm1",
            "https://lh3.googleusercontent.com/d/1xxXeom3VHNUDq4KJvlNtJ5zeusU6HFhp",
            "https://lh3.googleusercontent.com/d/1Jt6hvIx8YCH1YVXtvOvtZO338UcEJ4e8",
            "https://lh3.googleusercontent.com/d/1GXCI5d2ZKikendvZbbpSNoOGAYXlbk3C",
            "https://lh3.googleusercontent.com/d/1kGaB0lTlqnznIx4CJMxkK3grTXb9Uq7H",
            "https://lh3.googleusercontent.com/d/163-gy68YotX6DwGNC-S8jHk0zZQy-oS6",
            "https://lh3.googleusercontent.com/d/1vvFmf9nFywPy9AW3YoVEE14XguGEJfa1",
            "https://lh3.googleusercontent.com/d/1BYSviZWhiBYB1Oz3OxZxNet3R18eO813",
            "https://lh3.googleusercontent.com/d/1KdBqTOj63BfUvQ5I6xdjii1soA-hwnzc",
            "https://lh3.googleusercontent.com/d/1P3IyPpf46ChVdaW3uy2FK-mUBkhzlFi0",
            "https://lh3.googleusercontent.com/d/15SgmAbJcnoRYv8W5f4usyIHS7xND8jh3",
            "https://lh3.googleusercontent.com/d/1KRwwcw2J0BHTfccwVPTTUP12blGqS003",
            "https://lh3.googleusercontent.com/d/1Nb23Kqk0U3dHm73b7SD3b4XVAeORTyxp",
            "https://lh3.googleusercontent.com/d/1hflAiArdcsvB03A1fCONpaxOOV3bSYOp",
            "https://lh3.googleusercontent.com/d/1jS_vo-N5xaVA3N4NCEVNhDtwahXfEm2o",
            "https://lh3.googleusercontent.com/d/1NOvyY6qtXRIFsfeqNcVCpUG6oXeUqtmk",
            "https://lh3.googleusercontent.com/d/1D_W-nrCOtUC4ZZXdwUjcQ-2TT4OOyCs3",
            "https://lh3.googleusercontent.com/d/14T01Ar26FoeMXna4pJGCmEdKG1Jwa0-K",
            "https://lh3.googleusercontent.com/d/1U0tY-EaW74XA0k7Fd5E94oJsrUx8uKI3",
            "https://lh3.googleusercontent.com/d/1kyX1GIpIlXXfx7nia7BNhJgj051Rudba",
            "https://lh3.googleusercontent.com/d/1mk-nA1RH2u3PW5CmFPe3-XbU8tNd-_AL",
            "https://lh3.googleusercontent.com/d/1m1Rt1LcNRrAvG2LkO6qi81_aAynbZfJV",
            "https://lh3.googleusercontent.com/d/1N4IU-QzfKwDwg6yh5JuLg4uJgnUG3anF",
            "https://lh3.googleusercontent.com/d/1ZKrm2EW8fkvNphwzw4whWy2eiiaDhiCI"
        ],
        "videoUrl": "https://www.youtube.com/embed/urSzaDC-4Ss?autoplay=1&mute=1&loop=1&playlist=urSzaDC-4Ss&controls=0&showinfo=0&autohide=1&modestbranding=1",
        "order": 11,
        "ishidden": false,
        "isFeatured": true,
        "frameWidth": "",
        "frameHeight": "",
        "frameGlassEffect": "",
        "frameColor": "",
        "spotlightColor": "",
        "spotlightIntensity": "",
        "frameBorder": "",
        "frameShadow": "",
        "client": "",
        "role": "Museum / Experience Centre Graphic Designer",
        "year": "2025",
        "location": "Delhi",
        "softwareUsed": "Photoshop",
        "awards": "",
        "linkInstagram": "",
        "linkBehance": "",
        "linkVideo": "",
        "linkLive": "",
        "linkFigma": "",
        "linkPdf": "",
        "bannerUrl": "https://lh3.googleusercontent.com/d/1OWlikGqUz0E7O8nJqxMLtUKuHwwatmYs"
    },
    {
        "id": "sabarmati-ashram-memorial",
        "title": "Sabarmati Ashram Memorial",
        "subtitle": "Museum",
        "tags": "",
        "shortDescription": "Designed exhibition graphics celebrating the legacy of Mahatma Gandhi at Sabarmati Ashram Memorial.",
        "about": "Design meaningful exhibition graphics that communicate the life, values, and legacy of Mahatma Gandhi through clear visual storytelling, historically accurate content, and an engaging museum experience.",
        "approach": "",
        "conclusion": "Successfully delivered a cohesive visual communication system that enhanced historical storytelling, improved visitor engagement, and reinforced the memorial's educational and cultural experience through impactful exhibition graphics.",
        "roles": [
            "Designed exhibition graphics",
            "information panels",
            "wall graphics",
            "infographics",
            "and print-ready visual assets aligned with the memorial's narrative and visitor experience."
        ],
        "ctaLabel": "View Project",
        "ctaHref": "project-detail.html?id=sabarmati-ashram-memorial",
        "bannerImage": "https://lh3.googleusercontent.com/d/1WYKEx3z7fZzw7gR6a-EtlxKgZaxrbdmM",
        "images": [
            "https://lh3.googleusercontent.com/d/1uOah0Yb5Vza96LoG784tGV1eANmJ3Wjd",
            "https://lh3.googleusercontent.com/d/1qvzat6OybaZpD1r2pXO8syWZXZ8jHkBZ",
            "https://lh3.googleusercontent.com/d/1rXmBCDElLjdN8ctOFPpU8OfP7l0W0asY",
            "https://lh3.googleusercontent.com/d/1b77ArCRXWOSU5vsWzZszf9UfzVFc2sAz",
            "https://lh3.googleusercontent.com/d/1bH6_Oa5cEisEOTyOaj6bD4Jr3JonOykk",
            "https://lh3.googleusercontent.com/d/1JrjTnBsBlJkpD1Z-tXvlls77dgW5Vwbm",
            "https://lh3.googleusercontent.com/d/19py1l8jV82FaHgx0zKJ-rE7jigpbmT6Y",
            "https://lh3.googleusercontent.com/d/1a-oRW5Z_5sDJg1tuZxXcNeI7BJWKNktH",
            "https://lh3.googleusercontent.com/d/1wwhjFscVfi5KAXVoL72ASe-jIw35VkyP",
            "https://lh3.googleusercontent.com/d/10Ylj9ANCapCBa9yieRD8zUQrsCKKpHs-",
            "https://lh3.googleusercontent.com/d/1V9Av3Efjd_NHjJIezk_l37BVLlnguQ6M",
            "https://lh3.googleusercontent.com/d/1Yf-YuALuBSdIlfOf44aY9LYv8jQK5ESl",
            "https://lh3.googleusercontent.com/d/15IlGRo8L6VxAXudo2HBv83KSG-6id_nM",
            "https://lh3.googleusercontent.com/d/1Q2qVwTlYCQ936h3kgMLJ8cAClVAdNiJE",
            "https://lh3.googleusercontent.com/d/1QRrcjENBDHsbjE_bTCOlRBmLG-SFF1Hb",
            "https://lh3.googleusercontent.com/d/17JmTIUTsuJttsvWOKUp4pa4hROd1whnU",
            "https://lh3.googleusercontent.com/d/11Zby9yZL3PnziHgoaFqEWGUdMQPFRpGA",
            "https://lh3.googleusercontent.com/d/1ZbwOKZEO4jn_30gV_0qWbqXm9gnaSqR3",
            "https://lh3.googleusercontent.com/d/1r6YenFWvSp0Bh77KF8Hea9IPjReIL3Zq",
            "https://lh3.googleusercontent.com/d/19y8fOtAVyo74jI4Pyb7613_sq6hicuKW",
            "https://lh3.googleusercontent.com/d/1myV3xNyK2h4Skt4oDtuXEVhp2TbNQt7r",
            "https://lh3.googleusercontent.com/d/1cPaQJxud_1bgaa7isNBETdXO9vmreeLZ",
            "https://lh3.googleusercontent.com/d/19tyvaQ9Vp5r07AaqRlf4OnUbFZvc8OS1",
            "https://lh3.googleusercontent.com/d/1Q0uodWe5krzZiHBAHONZziMKbniGVi_5",
            "https://lh3.googleusercontent.com/d/1Zl_llNVoczYCMVfOwr8nqLXGeokywBF3"
        ],
        "videoUrl": "https://www.youtube.com/embed/x_zWSDlAoFQ?autoplay=1&mute=1&loop=1&playlist=x_zWSDlAoFQ&controls=0&showinfo=0&autohide=1&modestbranding=1",
        "order": 10,
        "ishidden": false,
        "isFeatured": true,
        "frameWidth": "",
        "frameHeight": "",
        "frameGlassEffect": "",
        "frameColor": "",
        "spotlightColor": "",
        "spotlightIntensity": "",
        "frameBorder": "",
        "frameShadow": "",
        "client": "",
        "role": "Museum Graphic Designer",
        "year": "2025",
        "location": "Delhi",
        "softwareUsed": "Photoshop",
        "awards": "",
        "linkInstagram": "",
        "linkBehance": "",
        "linkVideo": "",
        "linkLive": "",
        "linkFigma": "",
        "linkPdf": "",
        "bannerUrl": "https://lh3.googleusercontent.com/d/1WYKEx3z7fZzw7gR6a-EtlxKgZaxrbdmM"
    },
    {
        "id": "sanskriti-university",
        "title": "Sanskriti University",
        "subtitle": "Campaign",
        "tags": "",
        "shortDescription": "Designed newspaper ads, promotional banners, and TV L-band creatives for Sanskriti University.",
        "about": "Design impactful advertising creatives for Sanskriti University across newspaper, banners, and TV L-band formats while maintaining a strong institutional identity, clear communication, and effective promotional messaging.",
        "approach": "",
        "conclusion": "Successfully delivered high-quality advertising creatives across multiple media formats, enhancing the university's brand visibility, strengthening campaign communication, and supporting admissions and promotional initiatives.",
        "roles": [
            "Designed newspaper advertisements",
            "promotional banners",
            "and TV L-band creatives aligned with the university's branding and admission campaigns."
        ],
        "ctaLabel": "View Project",
        "ctaHref": "project-detail.html?id=sanskriti-university",
        "bannerImage": "https://lh3.googleusercontent.com/d/1P4HEvnfp0EjF7G3svVRmbTrCQNSIFkB_",
        "images": [
            "https://lh3.googleusercontent.com/d/1ClLEXLLxSYy6N4eqyNBpNN9m_AEiJdFT",
            "https://lh3.googleusercontent.com/d/1YLeCMf8Is2_zA7jTB65TIdSNk1efBSGY",
            "https://lh3.googleusercontent.com/d/1WIP52vlkVpiOiHDPIMxNxfS_O_Z32wDR",
            "https://lh3.googleusercontent.com/d/1BOdR-MzTbiwqI88qa3hHlwDPXC785GMI",
            "https://lh3.googleusercontent.com/d/1I4Ec8uieyGIy-V8it4g4X-qCTp5ZF5nf",
            "https://lh3.googleusercontent.com/d/1dNA5vsoYtIAJaUkRDIeIvesUlxHagDkI",
            "https://lh3.googleusercontent.com/d/1WTfMY48hwl0PJ1jC66aATKxA-2U2oa7e",
            "https://lh3.googleusercontent.com/d/17_ChVaI9d326_5-EJu-jM-uOzo5Dl3DK",
            "https://lh3.googleusercontent.com/d/1kKALFbnTSKkioAkPyRCpBsYgWlvXw2F3",
            "https://lh3.googleusercontent.com/d/1fBpbc0Ne7GkXbXy0Bdj5On6-q22C9yHS",
            "https://lh3.googleusercontent.com/d/1JbmYTmJDmCSurvso7Xjd4ZeyDYOImJDg",
            "https://lh3.googleusercontent.com/d/1eGllsCyBTLHLSquCvp6muC2Kli-7Zt1T",
            "https://lh3.googleusercontent.com/d/1QAWsMhxnbnuA-VKd7KcJ6U1DgHJAU-uw"
        ],
        "videoUrl": "https://drive.google.com/file/d/1P4HEvnfp0EjF7G3svVRmbTrCQNSIFkB_/preview",
        "order": 10,
        "ishidden": false,
        "isFeatured": false,
        "frameWidth": "",
        "frameHeight": "",
        "frameGlassEffect": "",
        "frameColor": "",
        "spotlightColor": "",
        "spotlightIntensity": "",
        "frameBorder": "",
        "frameShadow": "",
        "client": "",
        "role": "Graphic Designer",
        "year": "2024",
        "location": "Kanpur",
        "softwareUsed": "coreldraw, Photoshop",
        "awards": "",
        "linkInstagram": "",
        "linkBehance": "",
        "linkVideo": "",
        "linkLive": "",
        "linkFigma": "",
        "linkPdf": "",
        "bannerUrl": "https://lh3.googleusercontent.com/d/1P4HEvnfp0EjF7G3svVRmbTrCQNSIFkB_"
    },
    {
        "id": "shree-jugal-kishore-jewellers",
        "title": "Shree Jugal Kishore Jewellers",
        "subtitle": "Campaign",
        "tags": "",
        "shortDescription": "Designed newspaper ads, promotional banners, and TV L-band creatives for Shree Jugal Kishore Jewellers.",
        "about": "Design premium advertising creatives for Shree Jugal Kishore Jewellers across newspaper, banners, and TV L-band formats while reflecting the brand's elegance, craftsmanship, and festive appeal through impactful visual communication.",
        "approach": "",
        "conclusion": "Successfully delivered high-quality advertising creatives that enhanced brand visibility, strengthened promotional campaigns, and showcased the jeweller's premium identity across print and digital media.",
        "roles": [
            "Designed newspaper advertisements",
            "promotional banners",
            "and TV L-band creatives for festive and promotional marketing campaigns."
        ],
        "ctaLabel": "View Project",
        "ctaHref": "project-detail.html?id=shree-jugal-kishore-jewellers",
        "bannerImage": "https://lh3.googleusercontent.com/d/1Gj0r2r1NRecL3xZUwaXyvrRyECScvbGW",
        "images": [
            "https://lh3.googleusercontent.com/d/1-nSV1ctQQ1Aa2ZI3MMaOaGLW4RVisMUR",
            "https://lh3.googleusercontent.com/d/1PKFM_91JIjZ7yK-8gomxYbV-6paLHNWD",
            "https://lh3.googleusercontent.com/d/10nDptbnlJPnUrEnHvy4-uldzow3zjXoR",
            "https://lh3.googleusercontent.com/d/1fQ7W3sXrJiI68cGUmP37RIg224Kef60r",
            "https://lh3.googleusercontent.com/d/103UELDVSNYFPEmEM4XHB0_5eZHH-6zBQ",
            "https://lh3.googleusercontent.com/d/1MdNvIAcCeRAH1tBOoqmpqjD1GtBQzPtz",
            "https://lh3.googleusercontent.com/d/1J_JmMqdveE40SxcPqXgNRXl8k-2k5XnJ",
            "https://lh3.googleusercontent.com/d/1eI11PpMNNk-R15si1rJskwL9lS83N9iW"
        ],
        "videoUrl": "https://drive.google.com/file/d/1eI11PpMNNk-R15si1rJskwL9lS83N9iW/preview",
        "order": 10,
        "ishidden": false,
        "isFeatured": false,
        "frameWidth": "",
        "frameHeight": "",
        "frameGlassEffect": "",
        "frameColor": "",
        "spotlightColor": "",
        "spotlightIntensity": "",
        "frameBorder": "",
        "frameShadow": "",
        "client": "",
        "role": "Graphic Designer",
        "year": "2024",
        "location": "Kanpur",
        "softwareUsed": "coreldraw, Photoshop",
        "awards": "",
        "linkInstagram": "",
        "linkBehance": "",
        "linkVideo": "",
        "linkLive": "",
        "linkFigma": "",
        "linkPdf": "",
        "bannerUrl": "https://lh3.googleusercontent.com/d/1Gj0r2r1NRecL3xZUwaXyvrRyECScvbGW"
    },
    {
        "id": "virat-swaroop-projection-mapping",
        "title": "Virat Swaroop Projection Mapping",
        "subtitle": "Projection Mapping",
        "tags": "",
        "shortDescription": "Designed cinematic projection mapping visuals for the Virat Swaroop Light & Sound Show.",
        "about": "Create immersive projection mapping visuals that bring the grandeur of Virat Swaroop to life through cinematic storytelling, synchronized animations, and large-scale architectural projection, delivering a captivating Light & Sound Show experience.",
        "approach": "",
        "conclusion": "Successfully delivered immersive projection mapping content that transformed the architectural façade into a visually engaging storytelling experience, enhancing audience immersion through cinematic digital visuals and synchronized projection design.",
        "roles": [
            "Created high-resolution projection mapping visuals aligned with the story",
            "architecture",
            "and projection surface."
        ],
        "ctaLabel": "View Project",
        "ctaHref": "project-detail.html?id=virat-swaroop-projection-mapping",
        "bannerImage": "https://lh3.googleusercontent.com/d/11iAa4hIijOWWKJyf17HvLatbq7e0-OOi",
        "images": [
            "https://lh3.googleusercontent.com/d/1b20LfzgnpAbQ3HSxqbBOuK0tj47YSAIj",
            "https://lh3.googleusercontent.com/d/1aaQcvGYxBGXlCRdcFNcI0lSsdD2hi7JP",
            "https://lh3.googleusercontent.com/d/1w1oRTt0Rfn0SWUmMis74MBj2klkCLJqg",
            "https://lh3.googleusercontent.com/d/1u4_x_Ga3hunMRX7Qa0KziS8i_cNkNiX2",
            "https://lh3.googleusercontent.com/d/1MXVKjjT0709Fv9mwAk201lcDFeUw_141",
            "https://lh3.googleusercontent.com/d/1s-_XxCzS9yHsRxAXvwNzGCKGpedOP5Cz",
            "https://lh3.googleusercontent.com/d/10ehyd1WAUiwccwQoiMpTlire9bBddkVM",
            "https://lh3.googleusercontent.com/d/1ICjgM6tUODkPWL5c9uhkt51MoTXNHodz",
            "https://lh3.googleusercontent.com/d/1UzZDJyNjo36hssCLBH7OImbMSnbJLOfE",
            "https://lh3.googleusercontent.com/d/1RyTVT02AURENenN8mGGu48wJnh5Xag53",
            "https://www.youtube.com/embed/7Dle41YpzcY?autoplay=1&mute=1&loop=1&playlist=7Dle41YpzcY&controls=0&showinfo=0&autohide=1&modestbranding=1"
        ],
        "videoUrl": "https://www.youtube.com/embed/FxI5EPSRigI?autoplay=1&mute=1&loop=1&playlist=FxI5EPSRigI&controls=0&showinfo=0&autohide=1&modestbranding=1",
        "order": 10,
        "ishidden": false,
        "isFeatured": false,
        "frameWidth": "",
        "frameHeight": "",
        "frameGlassEffect": "",
        "frameColor": "",
        "spotlightColor": "",
        "spotlightIntensity": "",
        "frameBorder": "",
        "frameShadow": "",
        "client": "",
        "role": "Projection Mapping Visual Designer",
        "year": "2025",
        "location": "Delhi",
        "softwareUsed": "Photoshop",
        "awards": "",
        "linkInstagram": "",
        "linkBehance": "",
        "linkVideo": "",
        "linkLive": "",
        "linkFigma": "",
        "linkPdf": "",
        "bannerUrl": "https://lh3.googleusercontent.com/d/11iAa4hIijOWWKJyf17HvLatbq7e0-OOi"
    },
    {
        "id": "yuge-yugeen-bharat-museum",
        "title": "Yuge Yugeen Bharat Museum",
        "subtitle": "Museum",
        "tags": "",
        "shortDescription": "Designed museum graphics celebrating India's timeless heritage through immersive visual storytelling.",
        "about": "Design visually compelling museum graphics that present India's civilizational journey through engaging storytelling, culturally authentic visuals, and a cohesive exhibition experience.",
        "approach": "",
        "conclusion": "Delivered a cohesive visual identity for the museum through impactful exhibition graphics that enhanced storytelling, improved visitor engagement, and effectively communicated India's rich historical and cultural legacy.",
        "roles": [
            "Designed exhibition graphics",
            "information panels",
            "infographics",
            "and print-ready visual assets aligned with the museum's narrative and visitor experience."
        ],
        "ctaLabel": "View Project",
        "ctaHref": "project-detail.html?id=yuge-yugeen-bharat-museum",
        "bannerImage": "https://lh3.googleusercontent.com/d/1YSGocsIALeOQ2ra_tOQVmuhR9Jw8Nzyk",
        "images": [
            "https://lh3.googleusercontent.com/d/135JR_BQgqIAz_YZJdZtKWwBny3obGpew",
            "https://lh3.googleusercontent.com/d/1OAjXRfGiQBDDpgPAw1fWuGzp7i8Uot5T",
            "https://lh3.googleusercontent.com/d/1xT2GG8E41ifQoJ-s85XC-ywBX6ewMqFZ",
            "https://lh3.googleusercontent.com/d/1B_QkBVr8PWBg4pH028Rh__TDupuBIRWL",
            "https://lh3.googleusercontent.com/d/1rdh7QHVpg3ege6D1XOYsNWDWNSd8bdHX",
            "https://lh3.googleusercontent.com/d/1fs0CYWk9Rh5wucknYCbw9Ll3wspGMSxK",
            "https://lh3.googleusercontent.com/d/1rAux3Tnj-mQn-xkRPjlb6L92FiPSRyZ8",
            "https://lh3.googleusercontent.com/d/1ursYfBX-hH1Bq_yUoROWoqKyYw2jdm3P",
            "https://lh3.googleusercontent.com/d/1Nmqh_NGSKMUPXw2rYhQI5Dh-fVRnoHq1",
            "https://lh3.googleusercontent.com/d/1qgyOADwhtdfkjvOyUddNa0fG-vo3Mfz8",
            "https://lh3.googleusercontent.com/d/1mVnmd3TOoO4N4InhMgcBiCfuZxhdV_vM",
            "https://lh3.googleusercontent.com/d/10HPhyQNAl2UTAiy7WipK1b2VI7z1Ml0A",
            "https://lh3.googleusercontent.com/d/16tdm6t7fXtnxTPfSVysnUNPwmL_1eiPO",
            "https://lh3.googleusercontent.com/d/1kaCtsC06LzvzKgIXIHEAPkQDyQKPMbRC",
            "https://lh3.googleusercontent.com/d/1yA5jYCqbNGz1SbkeYNkMgpbC4xtK16OV",
            "https://lh3.googleusercontent.com/d/14IcFCSwDjiLXTosIPiRPyilIQPSiq8_U",
            "https://lh3.googleusercontent.com/d/1OHqFJ8o2YCgg3iksl3oPka-7pIt6Z9Rh",
            "https://lh3.googleusercontent.com/d/166VePI6iYvzZ6YHNFFuqZ1KEpZhSwNmL",
            "https://lh3.googleusercontent.com/d/1L3hMy6GUKNozJI_fA0FGWKz5rcOR0CyA",
            "https://lh3.googleusercontent.com/d/1UKuzoq_RmYYZePp7KmfPKfvPUYIMp0Y3",
            "https://lh3.googleusercontent.com/d/1VxnoV7P0lDEJ0PcF2rzq9IphtyAfNUEd",
            "https://lh3.googleusercontent.com/d/1wWdiLMMh5kndakehsyGnMKOQt-yZWElB",
            "https://lh3.googleusercontent.com/d/1_8bXQErkqNzi7OSBR0LcT1VSVIIkInUJ",
            "https://lh3.googleusercontent.com/d/1VNtqTOM9SBbBLKro2nzdwsx0HfIZMkBM",
            "https://lh3.googleusercontent.com/d/1_H63mPIB2jQK8PwkI2MgJkvcsaps62Fm"
        ],
        "videoUrl": "https://www.youtube.com/embed/W5Dxfw_HE2c?autoplay=1&mute=1&loop=1&playlist=W5Dxfw_HE2c&controls=0&showinfo=0&autohide=1&modestbranding=1",
        "order": 9,
        "ishidden": false,
        "isFeatured": true,
        "frameWidth": "",
        "frameHeight": "",
        "frameGlassEffect": "",
        "frameColor": "",
        "spotlightColor": "",
        "spotlightIntensity": "",
        "frameBorder": "",
        "frameShadow": "",
        "client": "",
        "role": "Museum Graphic Designer",
        "year": "2025",
        "location": "Delhi",
        "softwareUsed": "Photoshop",
        "awards": "",
        "linkInstagram": "",
        "linkBehance": "",
        "linkVideo": "",
        "linkLive": "",
        "linkFigma": "",
        "linkPdf": "",
        "bannerUrl": "https://lh3.googleusercontent.com/d/1YSGocsIALeOQ2ra_tOQVmuhR9Jw8Nzyk"
    },
    {
        "id": "dinosaur-fossil-national-park",
        "title": "Dinosaur Fossil National Park",
        "subtitle": "Museum & Experience",
        "tags": "",
        "shortDescription": "Designed museum graphics showcasing dinosaur fossils through engaging visual storytelling.",
        "about": "Design engaging exhibition graphics that communicate the prehistoric world, fossil discoveries, and scientific insights through immersive visual storytelling and an educational visitor experience.",
        "approach": "",
        "conclusion": "Successfully delivered a cohesive visual communication system that enhanced visitor engagement, simplified complex scientific information, and brought the story of dinosaur fossils to life through impactful exhibition graphics.",
        "roles": [
            "Designed exhibition graphics",
            "information panels",
            "infographics",
            "wall graphics",
            "interpretive signage",
            "and print-ready visual assets aligned with the museum's educational narrative."
        ],
        "ctaLabel": "View Project",
        "ctaHref": "project-detail.html?id=dinosaur-fossil-national-park",
        "bannerImage": "https://lh3.googleusercontent.com/d/16p7bjwIq4yGnFfCpWXYD19v-JFD67vDu",
        "images": [
            "https://lh3.googleusercontent.com/d/1uSxBayT-5BVIKHelOKLNJBjNcRLMcPm6",
            "https://lh3.googleusercontent.com/d/1NYa8hiF9qLWTpSrmEg7fT-rwG0l9Y-w0",
            "https://lh3.googleusercontent.com/d/15bVlDUfEEeGWNJQBwwZlD-r6V-Xbjdva",
            "https://lh3.googleusercontent.com/d/1ljeFUcxnpe97wjvT27ts4ZKO53hQuO1e",
            "https://lh3.googleusercontent.com/d/1i8xS990-mBpwM2dIi6f0H307WPyQL-j1",
            "https://lh3.googleusercontent.com/d/11A8-KI0ZrNS5878IAiimt4Hzr2v8PHgr",
            "https://lh3.googleusercontent.com/d/1Gk5Jx507rqk6x98Ohl59XH0d13-Vxnxg",
            "https://lh3.googleusercontent.com/d/1jXMf56xZ5KjvCb2yq5sYpdbArNPYUexK",
            "https://lh3.googleusercontent.com/d/1rBebk5v_Q2x7n-GvP5P1Buo8bfM_68Oz",
            "https://lh3.googleusercontent.com/d/1Kv2OxSRe6HobR0EIBGXWZtOtZp7INBk1",
            "https://lh3.googleusercontent.com/d/1A55yCP8Z06KaCT-mZ1H1GC93kB-JRyvc",
            "https://lh3.googleusercontent.com/d/1D1o98bd1AhSvo94xoa2_v5u3nxb7Cw6J",
            "https://lh3.googleusercontent.com/d/1jyk2WHEZc2jX6vkO4B_NTik2nO3f10W5",
            "https://lh3.googleusercontent.com/d/1_s3rUNjuT3gFbI7bd5yIhXMCMSH-7jh4",
            "https://lh3.googleusercontent.com/d/1trZSn5GI51N4z9LT8fUjVjh7ajf1jOs3",
            "https://lh3.googleusercontent.com/d/1c6VEAhNNNd8OzLgcQ9cJFR5UJz-5Nzlm",
            "https://lh3.googleusercontent.com/d/190JeAoGwe4F9kY-lGqAZz9tBbBnlQvTk",
            "https://lh3.googleusercontent.com/d/1pVUfuJBpKMyf_lNOe9wikrJ1DKTmjtDp",
            "https://lh3.googleusercontent.com/d/1aZEgWlU0S_dJjZNsqTDmqR9B5MXg0MQw",
            "https://lh3.googleusercontent.com/d/1xQaG8y0qoKB8jMpZ2WSrgcnM58eVv8Kf",
            "https://lh3.googleusercontent.com/d/1o5cJT_WGRmTjH1lwsju_nLqRhhg3xCHt",
            "https://lh3.googleusercontent.com/d/1OHNd2nIZXYvLYslWqsK8xWyky9be7Bwm",
            "https://lh3.googleusercontent.com/d/1a_qEtukrx_XdYpJFGJs_EoF52nB3M0Vw",
            "https://lh3.googleusercontent.com/d/1lPmlpsFmr7VS37u90xThQCs21Ay79eyR",
            "https://lh3.googleusercontent.com/d/135EB6WTF8851gbcmbadVx1Y9y9Ta3iCb"
        ],
        "videoUrl": "https://www.youtube.com/embed/8OHUTghG7HE?autoplay=1&mute=1&loop=1&playlist=8OHUTghG7HE&controls=0&showinfo=0&autohide=1&modestbranding=1",
        "order": 20,
        "ishidden": false,
        "isFeatured": true,
        "frameWidth": "",
        "frameHeight": "",
        "frameGlassEffect": "",
        "frameColor": "",
        "spotlightColor": "",
        "spotlightIntensity": "",
        "frameBorder": "",
        "frameShadow": "",
        "client": "",
        "role": "Museum Graphic Designer",
        "year": "2026",
        "location": "Delhi",
        "softwareUsed": "Photoshop",
        "awards": "",
        "linkInstagram": "",
        "linkBehance": "",
        "linkVideo": "",
        "linkLive": "",
        "linkFigma": "",
        "linkPdf": "",
        "bannerUrl": "https://lh3.googleusercontent.com/d/16p7bjwIq4yGnFfCpWXYD19v-JFD67vDu"
    },
    {
        "id": "hal-museum",
        "title": "HAL Museum",
        "subtitle": "Museum",
        "tags": "",
        "shortDescription": "Led the end-to-end visual design, projection mapping, and AI-powered multimedia for the HAL Museum.",
        "about": "Lead the complete visual design process from concept to execution, creating immersive museum graphics, projection mapping content, and AI-powered multimedia that showcase HAL's aerospace legacy, technological innovations, and achievements through engaging visual storytelling.",
        "approach": "",
        "conclusion": "Successfully delivered a unified museum experience by integrating exhibition graphics, projection mapping, and AI-generated multimedia into a cohesive storytelling system that enhanced visitor engagement, strengthened the museum's visual identity, and supported seamless execution from concept to installation.",
        "roles": [
            "Managed end-to-end visual design",
            "including concept development",
            "exhibition graphics",
            "projection mapping",
            "AI-generated visuals",
            "museum TV videos",
            "production artwork",
            "and on-site execution."
        ],
        "ctaLabel": "View Project",
        "ctaHref": "project-detail.html?id=hal-museum",
        "bannerImage": "https://lh3.googleusercontent.com/d/1mvlK9tT77IE0SDqqOpNs6XdgQKhz7C-H",
        "images": [
            "https://lh3.googleusercontent.com/d/1om3pJ5GEVs9iyY8IZmqqcmyEQSMqKsPr",
            "https://lh3.googleusercontent.com/d/13WWE8bF7KUJ33P4AAQVeo2bASE_b3oma",
            "https://www.youtube.com/embed/XUKW-AVvbms?autoplay=1&mute=1&loop=1&playlist=XUKW-AVvbms&controls=0&showinfo=0&autohide=1&modestbranding=1",
            "https://lh3.googleusercontent.com/d/16ER9DK3hQn5ec4t88yU95GewqR7pIjfn",
            "https://lh3.googleusercontent.com/d/1zr5WyyPTiS0rOOcs8p_nj50QXrXXIUJP",
            "https://lh3.googleusercontent.com/d/1UyB-4RqxanzaEFJUTEP8aovXvqepV6I7",
            "https://lh3.googleusercontent.com/d/1C3bphi64snOPoijaa6u0h5u2hhQvRt4z",
            "https://lh3.googleusercontent.com/d/1l0g_WAa77lvb8WnlAPmGeyx4pm0MDFeU",
            "https://lh3.googleusercontent.com/d/1aQ3lhYK4DmkcudS6P5YixN2hGLV9MhDl",
            "https://lh3.googleusercontent.com/d/1G5u6CMGsvNs5gP2lBO5RR6nfD5rJAC2Y",
            "https://lh3.googleusercontent.com/d/1KkIS7w8QF960njFttrqFu7Nmqr-XheUg",
            "https://lh3.googleusercontent.com/d/1McnbiAjKW9XseAnhuUePVw194_IKACQJ",
            "https://lh3.googleusercontent.com/d/1MquxC-dmgJ1deLWfssEy3XIMousmVgmK",
            "https://lh3.googleusercontent.com/d/1h-7oNFxDJaAnLEdrzUUJTPjwLp52ZfPT",
            "https://lh3.googleusercontent.com/d/1YdZiPZ39ZafDvEKjHIiSzfjl9ZH8TuXj",
            "https://lh3.googleusercontent.com/d/1mBRIP0VI-fP9m1zZijnd0AbpFdMid2-6",
            "https://lh3.googleusercontent.com/d/1i07xlvS-8tgqndcS6ts6Z1hQ8jsUGMIl",
            "https://lh3.googleusercontent.com/d/1y6t-1-LUAtPk_5FwFjqjPNVDWj0kKnGx",
            "https://lh3.googleusercontent.com/d/13gR15TqRZHg0ar5MFx9Ru7KXkk21bN9J",
            "https://lh3.googleusercontent.com/d/1UeS32zcA72iF58nStLABfz7yLqEouBhL",
            "https://lh3.googleusercontent.com/d/16jJA1tyAlooBnuI6IaXgjzrDe_PvI5oP",
            "https://lh3.googleusercontent.com/d/1t5TRK_BJvnycFuvL3gDeOa8bw9TTkq4G",
            "https://lh3.googleusercontent.com/d/1suKJ3t8uV_LmCaND6rtNo7mxSYBOim8i",
            "https://lh3.googleusercontent.com/d/1XLnuoY2JqXO1T4uGSz10nq1L21P5Fgyg",
            "https://lh3.googleusercontent.com/d/1Bx7wSOhv59l0HkurAWHJumgdnqf2pl10"
        ],
        "videoUrl": "https://www.youtube.com/embed/0JLmwxnSg5A?autoplay=1&mute=1&loop=1&playlist=0JLmwxnSg5A&controls=0&showinfo=0&autohide=1&modestbranding=1",
        "order": 21,
        "ishidden": false,
        "isFeatured": true,
        "frameWidth": "",
        "frameHeight": "",
        "frameGlassEffect": "",
        "frameColor": "",
        "spotlightColor": "",
        "spotlightIntensity": "",
        "frameBorder": "",
        "frameShadow": "",
        "client": "",
        "role": "Lead Museum Graphic Designer & Projection Mapping Visualizer",
        "year": "2025-2026",
        "location": "Bengaluru",
        "softwareUsed": "coreldraw, Photoshop",
        "awards": "",
        "linkInstagram": "",
        "linkBehance": "",
        "linkVideo": "",
        "linkLive": "",
        "linkFigma": "",
        "linkPdf": "",
        "bannerUrl": "https://lh3.googleusercontent.com/d/1mvlK9tT77IE0SDqqOpNs6XdgQKhz7C-H"
    }
];

function getAllProjects() {
    try {
        // Cleanup old keys
        for (let i = localStorage.length - 1; i >= 0; i--) {
            let k = localStorage.key(i);
            if (k && k.startsWith('sandeep_projects_') && k !== 'sandeep_projects_v25') {
                localStorage.removeItem(k);
              }
              if (k === 'sandeep_versions') {
                  localStorage.removeItem(k);
            }
        }
        const raw = localStorage.getItem('sandeep_projects_v25');
        if (raw === null) {
            try { localStorage.setItem('sandeep_projects_v25', JSON.stringify(DEFAULT_PROJECTS)); } catch(e){}
            return DEFAULT_PROJECTS;
        }
        let projects = JSON.parse(raw);
        
        // Self-healing: inject missing projects and merge missing images/banners
        let updated = false;
        for (const dp of DEFAULT_PROJECTS) {
            let existing = projects.find(p => p && p.id === dp.id);
            if (!existing) {
                projects.push(dp);
                updated = true;
            } else {
                // Do not override user's custom images or banner even if length differs.
            }
        }
        // Self-healing deduplication by ID
        const unique = [];
        const seen = new Set();
        for (const p of projects) {
            if (p && p.id && !seen.has(p.id)) {
                seen.add(p.id);
                unique.push(p);
            }
        }
        if (unique.length !== projects.length || updated) {
            try { localStorage.setItem('sandeep_projects_v25', JSON.stringify(unique)); } catch(e){}
        }
        return unique;
    } catch {
        return DEFAULT_PROJECTS;
    }
}

window.getAllProjects = getAllProjects;




















